/**
 * Country flags without a sports API.
 * Uses flagcdn.com (public flag images by ISO 3166-1 alpha-2).
 */

/** Common football / TM codes → ISO2 */
const CODE_TO_ISO2 = {
  TUR: 'tr',
  TR: 'tr',
  SMR: 'sm',
  ENG: 'gb-eng',
  SCO: 'gb-sct',
  WAL: 'gb-wls',
  NIR: 'gb-nir',
  GBR: 'gb',
  UK: 'gb',
  GER: 'de',
  DEU: 'de',
  FRA: 'fr',
  ESP: 'es',
  ITA: 'it',
  POR: 'pt',
  NED: 'nl',
  NLD: 'nl',
  BEL: 'be',
  AUT: 'at',
  SUI: 'ch',
  CHE: 'ch',
  POL: 'pl',
  CZE: 'cz',
  SVK: 'sk',
  HUN: 'hu',
  ROU: 'ro',
  BUL: 'bg',
  GRE: 'gr',
  GRC: 'gr',
  CRO: 'hr',
  SRB: 'rs',
  SVN: 'si',
  BIH: 'ba',
  MKD: 'mk',
  ALB: 'al',
  NOR: 'no',
  SWE: 'se',
  DEN: 'dk',
  DNK: 'dk',
  FIN: 'fi',
  ISL: 'is',
  IRL: 'ie',
  RUS: 'ru',
  UKR: 'ua',
  BLR: 'by',
  GEO: 'ge',
  ARM: 'am',
  AZE: 'az',
  KAZ: 'kz',
  ISR: 'il',
  CYP: 'cy',
  MLT: 'mt',
  LUX: 'lu',
  LIE: 'li',
  AND: 'ad',
  MNE: 'me',
  KOS: 'xk',
  FRO: 'fo',
  GIB: 'gi',
  BRA: 'br',
  ARG: 'ar',
  URU: 'uy',
  CHI: 'cl',
  CHL: 'cl',
  COL: 'co',
  PER: 'pe',
  ECU: 'ec',
  PAR: 'py',
  PRY: 'py',
  BOL: 'bo',
  VEN: 've',
  USA: 'us',
  MEX: 'mx',
  CAN: 'ca',
  CRC: 'cr',
  CRI: 'cr',
  HON: 'hn',
  HND: 'hn',
  PAN: 'pa',
  JAM: 'jm',
  TRI: 'tt',
  TTO: 'tt',
  JPN: 'jp',
  KOR: 'kr',
  CHN: 'cn',
  AUS: 'au',
  NZL: 'nz',
  KSA: 'sa',
  SAU: 'sa',
  QAT: 'qa',
  UAE: 'ae',
  IRN: 'ir',
  IRQ: 'iq',
  IND: 'in',
  THA: 'th',
  VIE: 'vn',
  IDN: 'id',
  MAS: 'my',
  MYS: 'my',
  SIN: 'sg',
  SGP: 'sg',
  EGY: 'eg',
  MAR: 'ma',
  TUN: 'tn',
  ALG: 'dz',
  DZA: 'dz',
  NGA: 'ng',
  GHA: 'gh',
  CIV: 'ci',
  SEN: 'sn',
  CMR: 'cm',
  RSA: 'za',
  ZAF: 'za',
  COD: 'cd',
  CGO: 'cg',
  ANG: 'ao',
  AGO: 'ao',
  MLI: 'ml',
  BFA: 'bf',
  GNB: 'gw',
  GUI: 'gn',
  GIN: 'gn',
  TOG: 'tg',
  TGO: 'tg',
  ZAM: 'zm',
  ZMB: 'zm',
  ZIM: 'zw',
  ZWE: 'zw',
  KEN: 'ke',
  UGA: 'ug',
  RWA: 'rw',
  ETH: 'et',
  MOZ: 'mz',
  MAD: 'mg',
  MDG: 'mg',
  CAF: 'cf',
  CTA: 'cf',
  GAB: 'ga',
  EQG: 'gq',
  GNQ: 'gq',
  NAM: 'na',
  BOT: 'bw',
  BWA: 'bw',
  LES: 'ls',
  LSO: 'ls',
  SWZ: 'sz',
  MRI: 'mu',
  MUS: 'mu',
  SEY: 'sc',
  SYC: 'sc',
  COM: 'km',
  CPV: 'cv',
  STP: 'st',
  LBR: 'lr',
  SLE: 'sl',
  GAM: 'gm',
  GMB: 'gm',
  NIG: 'ne',
  NER: 'ne',
  CHA: 'td',
  TCD: 'td',
  SUD: 'sd',
  SDN: 'sd',
  SSD: 'ss',
  ERI: 'er',
  DJI: 'dj',
  SOM: 'so',
  LBY: 'ly',
  MTN: 'mr',
  MRT: 'mr',
  // TM sometimes uses weird codes
  SMR1: 'sm',
  ENG1: 'gb-eng',
  ESP1: 'es',
  ITA1: 'it',
  GER1: 'de',
  FRA1: 'fr',
  POR1: 'pt',
  NED1: 'nl',
  BEL1: 'be',
  TUR1: 'tr',
}

export function toIso2(codeOrName) {
  if (!codeOrName) return null
  const raw = String(codeOrName).trim()
  const upper = raw.toUpperCase().replace(/[^A-Z0-9-]/g, '')
  if (CODE_TO_ISO2[upper]) return CODE_TO_ISO2[upper]
  // ARM1 → try first 3 letters
  const three = upper.slice(0, 3)
  if (CODE_TO_ISO2[three]) return CODE_TO_ISO2[three]
  if (/^[A-Z]{2}$/.test(upper)) return upper.toLowerCase()
  return null
}

/** 40px wide PNG from flagcdn (no API key). */
export function flagUrl(codeOrName, w = 40) {
  const iso = toIso2(codeOrName)
  if (!iso) return null
  return `https://flagcdn.com/w${w}/${iso}.png`
}

/** Unicode regional-indicator emoji when ISO2 known (not for eng/sct subdivisions). */
export function flagEmoji(codeOrName) {
  const iso = toIso2(codeOrName)
  if (!iso || iso.includes('-')) return null
  const cc = iso.toUpperCase()
  if (cc.length !== 2) return null
  return String.fromCodePoint(...[...cc].map((c) => 127397 + c.charCodeAt(0)))
}
