/* ------------------------------------------------------------------ */
/*  Club profiles (mock) — squad, manager, standings, tactics, window  */
/* ------------------------------------------------------------------ */

function p(shirt, name, age, nation, contract, value, playerId = null) {
  return { shirt, name, age, nation, contract, value, playerId }
}

function standRow(pos, club, code, pld, w, d, l, gf, ga, pts, form, highlight = false) {
  return { pos, club, code, pld, w, d, l, gf, ga, gd: gf - ga, pts, form, highlight }
}

export const CLUBS = {
  'fc-barcelona': {
    id: 'fc-barcelona',
    name: 'FC Barcelona',
    short: 'BAR',
    league: 'La Liga',
    leagueCode: 'LAL',
    country: 'Spain',
    founded: 1899,
    squadValue: 1124,
    squadSize: 26,
    avgAge: 25.1,
    foreignersPct: 54,
    stadium: {
      name: 'Spotify Camp Nou',
      capacity: 99354,
      pitch: '105 × 68 m',
      city: 'Barcelona',
    },
    manager: {
      name: 'Hansi Flick',
      managerId: 'flick',
      nation: 'GER',
      formation: '4-2-3-1',
      contractUntil: 2027,
      winPct: 74.2,
      matches: 62,
    },
    squad: {
      GK: [
        p(1, 'Marc-André ter Stegen', 34, 'GER', 'Jun 2028', 18),
        p(13, 'Iñaki Peña', 27, 'ESP', 'Jun 2026', 8),
        p(25, 'Wojciech Szczęsny', 36, 'POL', 'Jun 2026', 3),
      ],
      DEF: [
        p(3, 'Alejandro Balde', 22, 'ESP', 'Jun 2028', 55),
        p(4, 'Ronald Araújo', 27, 'URU', 'Jun 2031', 70),
        p(5, 'Iñigo Martínez', 35, 'ESP', 'Jun 2026', 6),
        p(23, 'Jules Koundé', 27, 'FRA', 'Jun 2027', 60),
        p(24, 'Eric García', 25, 'ESP', 'Jun 2026', 18),
        p(2, 'Pau Cubarsí', 19, 'ESP', 'Jun 2029', 50),
        p(35, 'Gerard Martín', 24, 'ESP', 'Jun 2028', 12),
      ],
      MID: [
        p(8, 'Pedri', 23, 'ESP', 'Jun 2030', 100),
        p(21, 'Frenkie de Jong', 29, 'NED', 'Jun 2026', 40),
        p(17, 'Marc Casadó', 22, 'ESP', 'Jun 2028', 35),
        p(6, 'Gavi', 21, 'ESP', 'Jun 2030', 70),
        p(20, 'Dani Olmo', 27, 'ESP', 'Jun 2030', 55),
        p(16, 'Fermín López', 23, 'ESP', 'Jun 2029', 40),
      ],
      FWD: [
        p(10, 'Lamine Yamal', 18, 'ESP', 'Jun 2031', 180, 'lamine-yamal'),
        p(9, 'Robert Lewandowski', 37, 'POL', 'Jun 2026', 12),
        p(11, 'Raphinha', 29, 'BRA', 'Jun 2027', 65),
        p(7, 'Ferran Torres', 26, 'ESP', 'Jun 2027', 35),
        p(19, 'Pau Víctor', 24, 'ESP', 'Jun 2029', 15),
        p(14, 'Ansu Fati', 23, 'ESP', 'Jun 2027', 25),
      ],
    },
    standings: [
      standRow(1, 'FC Barcelona', 'BAR', 28, 20, 5, 3, 68, 24, 65, ['W', 'W', 'D', 'W', 'W'], true),
      standRow(2, 'Real Madrid', 'RMA', 28, 19, 5, 4, 62, 28, 62, ['W', 'D', 'W', 'W', 'L']),
      standRow(3, 'Atlético Madrid', 'ATM', 28, 16, 8, 4, 48, 26, 56, ['D', 'W', 'W', 'D', 'W']),
      standRow(4, 'Athletic Club', 'ATH', 28, 14, 8, 6, 42, 28, 50, ['W', 'L', 'W', 'D', 'W']),
      standRow(5, 'Real Sociedad', 'RSO', 28, 12, 9, 7, 38, 32, 45, ['D', 'W', 'L', 'D', 'W']),
      standRow(6, 'Villarreal', 'VIL', 28, 12, 7, 9, 44, 40, 43, ['L', 'W', 'W', 'L', 'D']),
      standRow(7, 'Real Betis', 'BET', 28, 11, 8, 9, 36, 35, 41, ['W', 'D', 'L', 'W', 'D']),
      standRow(8, 'Sevilla', 'SEV', 28, 10, 8, 10, 34, 36, 38, ['L', 'D', 'W', 'L', 'W']),
    ],
    formation: '4-2-3-1',
    /* portrait pitch 0–100 x, 0–140 y, attack toward top */
    startingXI: [
      { shirt: 1, name: 'ter Stegen', pos: 'GK', x: 50, y: 122 },
      { shirt: 3, name: 'Balde', pos: 'LB', x: 18, y: 98 },
      { shirt: 2, name: 'Cubarsí', pos: 'CB', x: 38, y: 102 },
      { shirt: 4, name: 'Araújo', pos: 'CB', x: 62, y: 102 },
      { shirt: 23, name: 'Koundé', pos: 'RB', x: 82, y: 98 },
      { shirt: 17, name: 'Casadó', pos: 'DM', x: 38, y: 76 },
      { shirt: 8, name: 'Pedri', pos: 'CM', x: 62, y: 74 },
      { shirt: 11, name: 'Raphinha', pos: 'LW', x: 22, y: 48 },
      { shirt: 20, name: 'Olmo', pos: 'AM', x: 50, y: 52 },
      { shirt: 10, name: 'Yamal', pos: 'RW', x: 78, y: 48, playerId: 'lamine-yamal' },
      { shirt: 9, name: 'Lewandowski', pos: 'ST', x: 50, y: 28 },
    ],
    transfers: {
      arrivals: [
        { name: 'Dani Olmo', from: 'RB Leipzig', fee: 55, type: 'Transfer' },
        { name: 'Pau Víctor', from: 'Girona', fee: 12, type: 'Transfer' },
        { name: 'Szczęsny', from: 'Free agent', fee: 0, type: 'Free' },
      ],
      departures: [
        { name: 'Ilkay Gündoğan', to: 'Man City', fee: 0, type: 'Free' },
        { name: 'João Cancelo', to: 'Al-Hilal', fee: 25, type: 'Transfer' },
        { name: 'Vitor Roque', to: 'Betis', fee: null, type: 'Loan' },
      ],
    },
  },

  'real-madrid': {
    id: 'real-madrid',
    name: 'Real Madrid',
    short: 'RMA',
    league: 'La Liga',
    leagueCode: 'LAL',
    country: 'Spain',
    founded: 1902,
    squadValue: 1285,
    squadSize: 25,
    avgAge: 26.4,
    foreignersPct: 62,
    stadium: {
      name: 'Santiago Bernabéu',
      capacity: 81044,
      pitch: '105 × 68 m',
      city: 'Madrid',
    },
    manager: {
      name: 'Carlo Ancelotti',
      managerId: 'ancelotti',
      nation: 'ITA',
      formation: '4-3-3',
      contractUntil: 2026,
      winPct: 68.5,
      matches: 210,
    },
    squad: {
      GK: [
        p(1, 'Thibaut Courtois', 34, 'BEL', 'Jun 2026', 22),
        p(13, 'Andriy Lunin', 27, 'UKR', 'Jun 2030', 25),
      ],
      DEF: [
        p(2, 'Dani Carvajal', 34, 'ESP', 'Jun 2026', 8),
        p(22, 'Antonio Rüdiger', 33, 'GER', 'Jun 2026', 18),
        p(4, 'David Alaba', 33, 'AUT', 'Jun 2026', 12),
        p(23, 'Ferland Mendy', 30, 'FRA', 'Jun 2027', 20),
        p(35, 'Raúl Asencio', 22, 'ESP', 'Jun 2029', 28),
      ],
      MID: [
        p(5, 'Jude Bellingham', 22, 'ENG', 'Jun 2029', 180),
        p(8, 'Federico Valverde', 27, 'URU', 'Jun 2029', 120),
        p(15, 'Arda Güler', 21, 'TUR', 'Jun 2029', 60, 'arda-guler'),
        p(14, 'Aurélien Tchouaméni', 26, 'FRA', 'Jun 2028', 70),
        p(19, 'Dani Ceballos', 29, 'ESP', 'Jun 2027', 18),
      ],
      FWD: [
        p(7, 'Vinícius Júnior', 26, 'BRA', 'Jun 2027', 140, 'vinicius-junior'),
        p(11, 'Rodrygo', 25, 'BRA', 'Jun 2028', 90),
        p(9, 'Kylian Mbappé', 27, 'FRA', 'Jun 2029', 160),
        p(16, 'Endrick', 19, 'BRA', 'Jun 2030', 55),
      ],
    },
    standings: [
      standRow(1, 'FC Barcelona', 'BAR', 28, 20, 5, 3, 68, 24, 65, ['W', 'W', 'D', 'W', 'W']),
      standRow(2, 'Real Madrid', 'RMA', 28, 19, 5, 4, 62, 28, 62, ['W', 'D', 'W', 'W', 'L'], true),
      standRow(3, 'Atlético Madrid', 'ATM', 28, 16, 8, 4, 48, 26, 56, ['D', 'W', 'W', 'D', 'W']),
      standRow(4, 'Athletic Club', 'ATH', 28, 14, 8, 6, 42, 28, 50, ['W', 'L', 'W', 'D', 'W']),
      standRow(5, 'Real Sociedad', 'RSO', 28, 12, 9, 7, 38, 32, 45, ['D', 'W', 'L', 'D', 'W']),
    ],
    formation: '4-3-3',
    startingXI: [
      { shirt: 1, name: 'Courtois', pos: 'GK', x: 50, y: 122 },
      { shirt: 23, name: 'Mendy', pos: 'LB', x: 18, y: 98 },
      { shirt: 22, name: 'Rüdiger', pos: 'CB', x: 38, y: 102 },
      { shirt: 35, name: 'Asencio', pos: 'CB', x: 62, y: 102 },
      { shirt: 2, name: 'Carvajal', pos: 'RB', x: 82, y: 98 },
      { shirt: 14, name: 'Tchouaméni', pos: 'DM', x: 50, y: 78 },
      { shirt: 8, name: 'Valverde', pos: 'CM', x: 32, y: 62 },
      { shirt: 5, name: 'Bellingham', pos: 'CM', x: 68, y: 62 },
      { shirt: 7, name: 'Vinícius', pos: 'LW', x: 22, y: 40, playerId: 'vinicius-junior' },
      { shirt: 9, name: 'Mbappé', pos: 'ST', x: 50, y: 28 },
      { shirt: 11, name: 'Rodrygo', pos: 'RW', x: 78, y: 40 },
    ],
    transfers: {
      arrivals: [
        { name: 'Kylian Mbappé', from: 'PSG', fee: 0, type: 'Free' },
        { name: 'Endrick', from: 'Palmeiras', fee: 60, type: 'Transfer' },
      ],
      departures: [
        { name: 'Toni Kroos', to: 'Retired', fee: null, type: 'Free' },
        { name: 'Nacho', to: 'Al-Qadsiah', fee: 0, type: 'Free' },
      ],
    },
  },

  juventus: {
    id: 'juventus',
    name: 'Juventus',
    short: 'JUV',
    league: 'Serie A',
    leagueCode: 'SEA',
    country: 'Italy',
    founded: 1897,
    squadValue: 610,
    squadSize: 27,
    avgAge: 25.8,
    foreignersPct: 48,
    stadium: {
      name: 'Allianz Stadium',
      capacity: 41507,
      pitch: '105 × 68 m',
      city: 'Turin',
    },
    manager: {
      name: 'Igor Tudor',
      nation: 'CRO',
      formation: '3-4-2-1',
      contractUntil: 2027,
      winPct: 58.3,
      matches: 48,
    },
    squad: {
      GK: [
        p(1, 'Michele Di Gregorio', 28, 'ITA', 'Jun 2029', 28),
        p(29, 'Mattia Perin', 33, 'ITA', 'Jun 2027', 5),
      ],
      DEF: [
        p(3, 'Bremer', 28, 'BRA', 'Jun 2029', 55),
        p(4, 'Federico Gatti', 27, 'ITA', 'Jun 2028', 30),
        p(6, 'Danilo', 34, 'BRA', 'Jun 2026', 4),
        p(27, 'Andrea Cambiaso', 25, 'ITA', 'Jun 2029', 40),
      ],
      MID: [
        p(5, 'Manuel Locatelli', 28, 'ITA', 'Jun 2028', 35),
        p(8, 'Teun Koopmeiners', 28, 'NED', 'Jun 2029', 45),
        p(16, 'Weston McKennie', 27, 'USA', 'Jun 2027', 25),
        p(10, 'Kenan Yıldız', 21, 'TUR', 'Jun 2029', 75, 'kenan-yildiz'),
      ],
      FWD: [
        p(9, 'Dušan Vlahović', 26, 'SRB', 'Jun 2026', 55),
        p(7, 'Francisco Conceição', 22, 'POR', 'Jun 2029', 40),
        p(11, 'Nicolás González', 27, 'ARG', 'Jun 2028', 30),
      ],
    },
    standings: [
      standRow(1, 'Inter', 'INT', 28, 19, 6, 3, 58, 22, 63, ['W', 'W', 'D', 'W', 'W']),
      standRow(2, 'Napoli', 'NAP', 28, 18, 6, 4, 52, 24, 60, ['W', 'D', 'W', 'W', 'L']),
      standRow(3, 'Atalanta', 'ATA', 28, 16, 7, 5, 55, 28, 55, ['D', 'W', 'W', 'L', 'W']),
      standRow(4, 'Juventus', 'JUV', 28, 15, 9, 4, 46, 26, 54, ['W', 'D', 'W', 'D', 'W'], true),
      standRow(5, 'Milan', 'MIL', 28, 14, 8, 6, 48, 32, 50, ['L', 'W', 'W', 'D', 'W']),
    ],
    formation: '3-4-2-1',
    startingXI: [
      { shirt: 1, name: 'Di Gregorio', pos: 'GK', x: 50, y: 122 },
      { shirt: 27, name: 'Cambiaso', pos: 'LWB', x: 16, y: 88 },
      { shirt: 3, name: 'Bremer', pos: 'CB', x: 35, y: 100 },
      { shirt: 4, name: 'Gatti', pos: 'CB', x: 50, y: 104 },
      { shirt: 6, name: 'Danilo', pos: 'CB', x: 65, y: 100 },
      { shirt: 16, name: 'McKennie', pos: 'RWB', x: 84, y: 88 },
      { shirt: 5, name: 'Locatelli', pos: 'CM', x: 38, y: 70 },
      { shirt: 8, name: 'Koopmeiners', pos: 'CM', x: 62, y: 70 },
      { shirt: 10, name: 'Yıldız', pos: 'AM', x: 38, y: 48, playerId: 'kenan-yildiz' },
      { shirt: 7, name: 'Conceição', pos: 'AM', x: 62, y: 48 },
      { shirt: 9, name: 'Vlahović', pos: 'ST', x: 50, y: 28 },
    ],
    transfers: {
      arrivals: [
        { name: 'Teun Koopmeiners', from: 'Atalanta', fee: 54, type: 'Transfer' },
        { name: 'Francisco Conceição', from: 'Porto', fee: 30, type: 'Transfer' },
      ],
      departures: [
        { name: 'Adrien Rabiot', to: 'Marseille', fee: 0, type: 'Free' },
        { name: 'Federico Chiesa', to: 'Liverpool', fee: 15, type: 'Transfer' },
      ],
    },
  },

  'bayern-munich': {
    id: 'bayern-munich',
    name: 'Bayern Munich',
    short: 'FCB',
    league: 'Bundesliga',
    leagueCode: 'BUN',
    country: 'Germany',
    founded: 1900,
    squadValue: 980,
    squadSize: 25,
    avgAge: 25.6,
    foreignersPct: 56,
    stadium: {
      name: 'Allianz Arena',
      capacity: 75024,
      pitch: '105 × 68 m',
      city: 'Munich',
    },
    manager: {
      name: 'Vincent Kompany',
      managerId: 'kompany',
      nation: 'BEL',
      formation: '4-2-3-1',
      contractUntil: 2027,
      winPct: 71.0,
      matches: 55,
    },
    squad: {
      GK: [
        p(1, 'Manuel Neuer', 39, 'GER', 'Jun 2026', 4),
        p(26, 'Sven Ulreich', 37, 'GER', 'Jun 2026', 1),
      ],
      DEF: [
        p(3, 'Kim Min-jae', 29, 'KOR', 'Jun 2028', 40),
        p(2, 'Dayot Upamecano', 27, 'FRA', 'Jun 2026', 35),
        p(19, 'Alphonso Davies', 25, 'CAN', 'Jun 2025', 50),
        p(22, 'Raphaël Guerreiro', 32, 'POR', 'Jun 2026', 10),
      ],
      MID: [
        p(42, 'Jamal Musiala', 23, 'GER', 'Jun 2030', 125, 'jamal-musiala'),
        p(6, 'Joshua Kimmich', 31, 'GER', 'Jun 2026', 45),
        p(8, 'Leon Goretzka', 31, 'GER', 'Jun 2026', 25),
        p(45, 'Aleksandar Pavlović', 21, 'GER', 'Jun 2029', 45),
      ],
      FWD: [
        p(17, 'Michael Olise', 24, 'FRA', 'Jun 2029', 110, 'michael-olise'),
        p(9, 'Harry Kane', 32, 'ENG', 'Jun 2027', 80),
        p(7, 'Serge Gnabry', 30, 'GER', 'Jun 2026', 30),
        p(10, 'Leroy Sané', 30, 'GER', 'Jun 2026', 40),
      ],
    },
    standings: [
      standRow(1, 'Bayern Munich', 'FCB', 26, 20, 4, 2, 78, 22, 64, ['W', 'W', 'W', 'D', 'W'], true),
      standRow(2, 'Leverkusen', 'B04', 26, 16, 6, 4, 58, 28, 54, ['W', 'D', 'W', 'L', 'W']),
      standRow(3, 'Dortmund', 'BVB', 26, 14, 6, 6, 52, 34, 48, ['L', 'W', 'W', 'D', 'W']),
      standRow(4, 'RB Leipzig', 'RBL', 26, 13, 7, 6, 48, 32, 46, ['D', 'W', 'L', 'W', 'D']),
      standRow(5, 'Frankfurt', 'SGE', 26, 12, 7, 7, 44, 36, 43, ['W', 'L', 'D', 'W', 'W']),
    ],
    formation: '4-2-3-1',
    startingXI: [
      { shirt: 1, name: 'Neuer', pos: 'GK', x: 50, y: 122 },
      { shirt: 19, name: 'Davies', pos: 'LB', x: 18, y: 98 },
      { shirt: 3, name: 'Kim', pos: 'CB', x: 38, y: 102 },
      { shirt: 2, name: 'Upamecano', pos: 'CB', x: 62, y: 102 },
      { shirt: 22, name: 'Guerreiro', pos: 'RB', x: 82, y: 98 },
      { shirt: 6, name: 'Kimmich', pos: 'DM', x: 38, y: 76 },
      { shirt: 45, name: 'Pavlović', pos: 'DM', x: 62, y: 76 },
      { shirt: 10, name: 'Sané', pos: 'LW', x: 22, y: 48 },
      { shirt: 42, name: 'Musiala', pos: 'AM', x: 50, y: 52, playerId: 'jamal-musiala' },
      { shirt: 17, name: 'Olise', pos: 'RW', x: 78, y: 48, playerId: 'michael-olise' },
      { shirt: 9, name: 'Kane', pos: 'ST', x: 50, y: 28 },
    ],
    transfers: {
      arrivals: [
        { name: 'Michael Olise', from: 'Crystal Palace', fee: 53, type: 'Transfer' },
        { name: 'João Palhinha', from: 'Fulham', fee: 51, type: 'Transfer' },
      ],
      departures: [
        { name: 'Thomas Müller', to: 'Vancouver', fee: 0, type: 'Free' },
        { name: 'Matthijs de Ligt', to: 'Man United', fee: 45, type: 'Transfer' },
      ],
    },
  },

  psg: {
    id: 'psg',
    name: 'Paris Saint-Germain',
    short: 'PSG',
    league: 'Ligue 1',
    leagueCode: 'LI1',
    country: 'France',
    founded: 1970,
    squadValue: 920,
    squadSize: 28,
    avgAge: 24.2,
    foreignersPct: 61,
    stadium: {
      name: 'Parc des Princes',
      capacity: 47929,
      pitch: '105 × 68 m',
      city: 'Paris',
    },
    manager: {
      name: 'Luis Enrique',
      managerId: 'luis-enrique',
      nation: 'ESP',
      formation: '4-3-3',
      contractUntil: 2027,
      winPct: 69.8,
      matches: 88,
    },
    squad: {
      GK: [
        p(1, 'Gianluigi Donnarumma', 27, 'ITA', 'Jun 2026', 50),
        p(80, 'Arnau Tenas', 24, 'ESP', 'Jun 2028', 8),
      ],
      DEF: [
        p(5, 'Marquinhos', 31, 'BRA', 'Jun 2028', 40),
        p(2, 'Achraf Hakimi', 27, 'MAR', 'Jun 2026', 55),
        p(25, 'Nuno Mendes', 23, 'POR', 'Jun 2026', 50),
        p(51, 'Willian Pacho', 24, 'ECU', 'Jun 2029', 40),
      ],
      MID: [
        p(17, 'Vitinha', 25, 'POR', 'Jun 2027', 70),
        p(8, 'Fabián Ruiz', 29, 'ESP', 'Jun 2027', 35),
        p(87, 'João Neves', 21, 'POR', 'Jun 2029', 70),
        p(14, 'Désiré Doué', 21, 'FRA', 'Jun 2029', 90, 'desire-doue'),
      ],
      FWD: [
        p(10, 'Ousmane Dembélé', 28, 'FRA', 'Jun 2028', 70),
        p(7, 'Khvicha Kvaratskhelia', 25, 'GEO', 'Jun 2029', 80),
        p(9, 'Gonçalo Ramos', 24, 'POR', 'Jun 2028', 45),
        p(29, 'Bradley Barcola', 23, 'FRA', 'Jun 2028', 60),
      ],
    },
    standings: [
      standRow(1, 'Paris SG', 'PSG', 26, 21, 4, 1, 72, 20, 67, ['W', 'W', 'W', 'W', 'D'], true),
      standRow(2, 'Monaco', 'ASM', 26, 15, 6, 5, 52, 30, 51, ['W', 'D', 'L', 'W', 'W']),
      standRow(3, 'Marseille', 'OM', 26, 14, 6, 6, 48, 32, 48, ['L', 'W', 'W', 'D', 'W']),
      standRow(4, 'Lille', 'LIL', 26, 13, 7, 6, 42, 28, 46, ['D', 'W', 'W', 'L', 'D']),
      standRow(5, 'Lyon', 'OL', 26, 12, 6, 8, 44, 36, 42, ['W', 'L', 'D', 'W', 'W']),
    ],
    formation: '4-3-3',
    startingXI: [
      { shirt: 1, name: 'Donnarumma', pos: 'GK', x: 50, y: 122 },
      { shirt: 25, name: 'Mendes', pos: 'LB', x: 18, y: 98 },
      { shirt: 51, name: 'Pacho', pos: 'CB', x: 38, y: 102 },
      { shirt: 5, name: 'Marquinhos', pos: 'CB', x: 62, y: 102 },
      { shirt: 2, name: 'Hakimi', pos: 'RB', x: 82, y: 98 },
      { shirt: 87, name: 'Neves', pos: 'CM', x: 32, y: 70 },
      { shirt: 17, name: 'Vitinha', pos: 'CM', x: 50, y: 72 },
      { shirt: 14, name: 'Doué', pos: 'CM', x: 68, y: 70, playerId: 'desire-doue' },
      { shirt: 7, name: 'Kvaratskhelia', pos: 'LW', x: 22, y: 40 },
      { shirt: 9, name: 'Ramos', pos: 'ST', x: 50, y: 28 },
      { shirt: 10, name: 'Dembélé', pos: 'RW', x: 78, y: 40 },
    ],
    transfers: {
      arrivals: [
        { name: 'Désiré Doué', from: 'Rennes', fee: 50, type: 'Transfer' },
        { name: 'João Neves', from: 'Benfica', fee: 60, type: 'Transfer' },
        { name: 'Khvicha Kvaratskhelia', from: 'Napoli', fee: 70, type: 'Transfer' },
      ],
      departures: [
        { name: 'Kylian Mbappé', to: 'Real Madrid', fee: 0, type: 'Free' },
        { name: 'Marco Asensio', to: 'Aston Villa', fee: null, type: 'Loan' },
      ],
    },
  },
}

export const CLUB_BY_SHORT = Object.fromEntries(
  Object.values(CLUBS).map((c) => [c.short, c.id]),
)
