/* ------------------------------------------------------------------ */
/*  Mock data layer (replaced by API in later steps)                   */
/* ------------------------------------------------------------------ */

export const PLAYERS = {
  'lamine-yamal': {
    id: 'lamine-yamal',
    name: 'Lamine Yamal',
    shirt: 10,
    club: 'FC Barcelona',
    clubShort: 'BAR',
    clubId: 'fc-barcelona',
    nationId: 'spain',
    league: 'La Liga',
    position: 'Right Winger',
    age: 18,
    nation: { code: 'ESP', name: 'Spain' },
    foot: 'Left',
    contractUntil: 2031,
    value: 180,
    trendPct: 12.5,
    valueHistory: [
      { year: 2022, value: 5 },
      { year: 2023, value: 15 },
      { year: 2024, value: 60 },
      { year: 2025, value: 90 },
      { year: 2026, value: 180 },
    ],
    seasonStats: { matches: 41, goals: 18, assists: 22, minutes: 3412 },
    transfers: [
      { date: 'Apr 2023', year: 2023, from: 'Barcelona Juvenil A', to: 'FC Barcelona', fee: null, type: 'Promotion', marketValue: 5 },
      { date: 'Jul 2022', year: 2022, from: 'Barcelona U16', to: 'Barcelona Juvenil A', fee: null, type: 'Youth', marketValue: 0.5 },
      { date: 'Jul 2014', year: 2014, from: 'CF La Torreta', to: 'La Masia Academy', fee: null, type: 'Youth', marketValue: null },
    ],
  },
  'vinicius-junior': {
    id: 'vinicius-junior',
    name: 'Vinícius Júnior',
    shirt: 7,
    club: 'Real Madrid',
    clubShort: 'RMA',
    clubId: 'real-madrid',
    nationId: 'brazil',
    league: 'La Liga',
    position: 'Left Winger',
    age: 26,
    nation: { code: 'BRA', name: 'Brazil' },
    foot: 'Right',
    contractUntil: 2027,
    value: 140,
    trendPct: -6.7,
    valueHistory: [
      { year: 2022, value: 100 },
      { year: 2023, value: 120 },
      { year: 2024, value: 150 },
      { year: 2025, value: 150 },
      { year: 2026, value: 140 },
    ],
    seasonStats: { matches: 44, goals: 24, assists: 11, minutes: 3618 },
    transfers: [
      { date: 'Jul 2018', year: 2018, from: 'Flamengo', to: 'Real Madrid', fee: 45, type: 'Transfer', marketValue: 40 },
      { date: 'May 2017', year: 2017, from: 'Flamengo U20', to: 'Flamengo', fee: null, type: 'Promotion', marketValue: 8 },
      { date: 'Jan 2017', year: 2017, from: 'Flamengo U17', to: 'Flamengo U20', fee: null, type: 'Youth', marketValue: 2 },
      { date: 'Jul 2010', year: 2010, from: 'Caju', to: 'Flamengo Youth', fee: null, type: 'Youth', marketValue: null },
    ],
  },
  'kenan-yildiz': {
    id: 'kenan-yildiz',
    name: 'Kenan Yıldız',
    shirt: 10,
    club: 'Juventus',
    clubShort: 'JUV',
    clubId: 'juventus',
    nationId: 'turkiye',
    league: 'Serie A',
    position: 'Attacking Midfield',
    age: 21,
    nation: { code: 'TUR', name: 'Türkiye' },
    foot: 'Right',
    contractUntil: 2029,
    value: 75,
    trendPct: 25.0,
    valueHistory: [
      { year: 2022, value: 3 },
      { year: 2023, value: 15 },
      { year: 2024, value: 30 },
      { year: 2025, value: 60 },
      { year: 2026, value: 75 },
    ],
    seasonStats: { matches: 39, goals: 14, assists: 9, minutes: 3105 },
    transfers: [
      { date: 'Jul 2022', year: 2022, from: 'Bayern Munich U19', to: 'Juventus', fee: null, type: 'Free', marketValue: 3 },
      { date: 'Jul 2019', year: 2019, from: 'Bayern U17', to: 'Bayern Munich U19', fee: null, type: 'Youth', marketValue: 0.5 },
      { date: 'Jul 2012', year: 2012, from: 'SpVgg Grün-Weiß', to: 'Bayern Munich Youth', fee: null, type: 'Youth', marketValue: null },
    ],
  },
  'arda-guler': {
    id: 'arda-guler',
    name: 'Arda Güler',
    shirt: 15,
    club: 'Real Madrid',
    clubShort: 'RMA',
    clubId: 'real-madrid',
    nationId: 'turkiye',
    league: 'La Liga',
    position: 'Attacking Midfield',
    age: 21,
    nation: { code: 'TUR', name: 'Türkiye' },
    foot: 'Left',
    contractUntil: 2029,
    value: 60,
    trendPct: 33.3,
    valueHistory: [
      { year: 2022, value: 17 },
      { year: 2023, value: 25 },
      { year: 2024, value: 30 },
      { year: 2025, value: 45 },
      { year: 2026, value: 60 },
    ],
    seasonStats: { matches: 35, goals: 9, assists: 12, minutes: 2280 },
    transfers: [
      { date: 'Jul 2023', year: 2023, from: 'Fenerbahçe', to: 'Real Madrid', fee: 20, type: 'Transfer', marketValue: 17 },
      { date: 'Aug 2021', year: 2021, from: 'Fenerbahçe U19', to: 'Fenerbahçe', fee: null, type: 'Promotion', marketValue: 1.5 },
      { date: 'Sep 2019', year: 2019, from: 'Gençlerbirliği Youth', to: 'Fenerbahçe Youth', fee: null, type: 'Youth', marketValue: null },
    ],
  },
  'desire-doue': {
    id: 'desire-doue',
    name: 'Désiré Doué',
    shirt: 14,
    club: 'Paris Saint-Germain',
    clubShort: 'PSG',
    clubId: 'psg',
    nationId: 'france',
    league: 'Ligue 1',
    position: 'Attacking Midfield',
    age: 21,
    nation: { code: 'FRA', name: 'France' },
    foot: 'Right',
    contractUntil: 2029,
    value: 90,
    trendPct: 25.0,
    valueHistory: [
      { year: 2022, value: 4 },
      { year: 2023, value: 15 },
      { year: 2024, value: 50 },
      { year: 2025, value: 72 },
      { year: 2026, value: 90 },
    ],
    seasonStats: { matches: 42, goals: 13, assists: 15, minutes: 3010 },
    transfers: [
      { date: 'Aug 2024', year: 2024, from: 'Stade Rennais', to: 'Paris Saint-Germain', fee: 50, type: 'Transfer', marketValue: 50 },
      { date: 'Jul 2022', year: 2022, from: 'Rennes U19', to: 'Stade Rennais', fee: null, type: 'Promotion', marketValue: 4 },
      { date: 'Jul 2017', year: 2017, from: 'Rennes Youth', to: 'Rennes U19', fee: null, type: 'Youth', marketValue: null },
    ],
  },
  'michael-olise': {
    id: 'michael-olise',
    name: 'Michael Olise',
    shirt: 17,
    club: 'Bayern Munich',
    clubShort: 'FCB',
    clubId: 'bayern-munich',
    nationId: 'france',
    league: 'Bundesliga',
    position: 'Right Winger',
    age: 24,
    nation: { code: 'FRA', name: 'France' },
    foot: 'Left',
    contractUntil: 2029,
    value: 110,
    trendPct: 10.0,
    valueHistory: [
      { year: 2022, value: 25 },
      { year: 2023, value: 40 },
      { year: 2024, value: 55 },
      { year: 2025, value: 100 },
      { year: 2026, value: 110 },
    ],
    seasonStats: { matches: 40, goals: 17, assists: 14, minutes: 3390 },
    transfers: [
      { date: 'Jul 2024', year: 2024, from: 'Crystal Palace', to: 'Bayern Munich', fee: 53, type: 'Transfer', marketValue: 55 },
      { date: 'Jul 2021', year: 2021, from: 'Reading FC', to: 'Crystal Palace', fee: 9.5, type: 'Transfer', marketValue: 8 },
      { date: 'Jul 2017', year: 2017, from: 'Chelsea U18', to: 'Reading FC', fee: null, type: 'Free', marketValue: 0.2 },
      { date: 'Jul 2016', year: 2016, from: 'Chelsea Youth', to: 'Chelsea U18', fee: null, type: 'Youth', marketValue: null },
    ],
  },
  'jamal-musiala': {
    id: 'jamal-musiala',
    name: 'Jamal Musiala',
    shirt: 42,
    club: 'Bayern Munich',
    clubShort: 'FCB',
    clubId: 'bayern-munich',
    nationId: 'germany',
    league: 'Bundesliga',
    position: 'Attacking Midfield',
    age: 23,
    nation: { code: 'GER', name: 'Germany' },
    foot: 'Right',
    contractUntil: 2030,
    value: 125,
    trendPct: -3.8,
    valueHistory: [
      { year: 2022, value: 100 },
      { year: 2023, value: 110 },
      { year: 2024, value: 120 },
      { year: 2025, value: 130 },
      { year: 2026, value: 125 },
    ],
    seasonStats: { matches: 33, goals: 12, assists: 10, minutes: 2554 },
    transfers: [
      { date: 'Jul 2019', year: 2019, from: 'Chelsea U18', to: 'Bayern Munich', fee: null, type: 'Free', marketValue: 0.5 },
      { date: 'Jul 2014', year: 2014, from: 'Southampton Youth', to: 'Chelsea Youth', fee: null, type: 'Youth', marketValue: null },
      { date: 'Jul 2011', year: 2011, from: 'TSV Lehnerz', to: 'Southampton Youth', fee: null, type: 'Youth', marketValue: null },
    ],
  },
}

export const MVP = {
  playerId: 'lamine-yamal',
  name: 'Lamine Yamal',
  club: 'FC Barcelona',
  position: 'Right Winger',
  age: 18,
  nation: 'Spain',
  value: 180,
  delta: +20,
  // 12-month market value trajectory (€M)
  history: [90, 100, 110, 120, 120, 130, 140, 150, 150, 160, 160, 180],
}

export const RUMOR = {
  playerId: 'kenan-yildiz',
  player: 'Kenan Yıldız',
  position: 'Attacking Midfield',
  from: { name: 'Juventus', short: 'JUV' },
  to: { name: 'Chelsea FC', short: 'CHE' },
  probability: 68,
  fee: '€95M',
  source: 'Fabrizio Romano',
  updated: '2h ago',
}

export const MOVERS = [
  { playerId: 'desire-doue', name: 'Désiré Doué', club: 'Paris Saint-Germain', value: 90, delta: +18 },
  { playerId: 'arda-guler', name: 'Arda Güler', club: 'Real Madrid', value: 60, delta: +15 },
  { playerId: 'michael-olise', name: 'Michael Olise', club: 'Bayern Munich', value: 110, delta: +10 },
  { playerId: 'vinicius-junior', name: 'Vinícius Júnior', club: 'Real Madrid', value: 140, delta: -10 },
  { playerId: 'jamal-musiala', name: 'Jamal Musiala', club: 'Bayern Munich', value: 125, delta: -5 },
]

export const SEARCH_INDEX = [
  { type: 'Player', label: 'Lamine Yamal', meta: 'FC Barcelona · €180M', playerId: 'lamine-yamal' },
  { type: 'Player', label: 'Kenan Yıldız', meta: 'Juventus · €75M', playerId: 'kenan-yildiz' },
  { type: 'Player', label: 'Arda Güler', meta: 'Real Madrid · €60M', playerId: 'arda-guler' },
  { type: 'Player', label: 'Jamal Musiala', meta: 'Bayern Munich · €125M', playerId: 'jamal-musiala' },
  { type: 'Player', label: 'Vinícius Júnior', meta: 'Real Madrid · €140M', playerId: 'vinicius-junior' },
  { type: 'Player', label: 'Désiré Doué', meta: 'Paris Saint-Germain · €90M', playerId: 'desire-doue' },
  { type: 'Player', label: 'Michael Olise', meta: 'Bayern Munich · €110M', playerId: 'michael-olise' },
  { type: 'Club', label: 'FC Barcelona', meta: 'La Liga · Squad value €1.12B', clubId: 'fc-barcelona' },
  { type: 'Club', label: 'Real Madrid', meta: 'La Liga · Squad value €1.29B', clubId: 'real-madrid' },
  { type: 'Club', label: 'Juventus', meta: 'Serie A · Squad value €610M', clubId: 'juventus' },
  { type: 'Club', label: 'Bayern Munich', meta: 'Bundesliga · Squad value €980M', clubId: 'bayern-munich' },
  { type: 'Club', label: 'Paris Saint-Germain', meta: 'Ligue 1 · Squad value €920M', clubId: 'psg' },
  { type: 'Rumor', label: 'Kenan Yıldız → Chelsea', meta: '68% probability · €95M', playerId: 'kenan-yildiz' },
  { type: 'Rumor', label: 'Musiala → Manchester City', meta: '31% probability · €140M', playerId: 'jamal-musiala' },
  { type: 'Match', label: 'Bayern Munich vs Leverkusen', meta: 'FT · 3-2 · Bundesliga', matchId: 'bayern-leverkusen' },
  { type: 'Match', label: 'Barcelona vs Real Madrid', meta: 'Live 67′ · 2-1 · La Liga', matchId: 'barcelona-real-madrid' },
  { type: 'Match', label: 'PSG vs Monaco', meta: 'FT · 4-0 · Ligue 1', matchId: 'psg-monaco' },
  { type: 'Match', label: 'Juventus vs Inter', meta: 'Live 54′ · 1-1 · Serie A', matchId: 'juventus-inter' },
  { type: 'Match', label: 'Chelsea vs Arsenal', meta: 'Live 23′ · 0-0 · Premier League', matchId: 'chelsea-arsenal' },
  { type: 'Match', label: 'Liverpool vs Man City', meta: 'Upcoming 21:00 · Premier League', matchId: 'liverpool-man-city' },
  { type: 'League', label: 'La Liga', meta: 'Spain · €6.11bn market value', leagueId: 'la-liga' },
  { type: 'League', label: 'Premier League', meta: 'England · €11.24bn market value', leagueId: 'premier-league' },
  { type: 'League', label: 'Bundesliga', meta: 'Germany · €4.02bn market value', leagueId: 'bundesliga' },
  { type: 'League', label: 'Serie A', meta: 'Italy · €4.87bn market value', leagueId: 'serie-a' },
  { type: 'League', label: 'Ligue 1', meta: 'France · €3.55bn market value', leagueId: 'ligue-1' },
  { type: 'League', label: 'Trendyol Süper Lig', meta: 'Türkiye · €1.12bn market value', leagueId: 'super-lig' },
  { type: 'League', label: 'UEFA Champions League', meta: 'Europe · League phase', leagueId: 'ucl' },
  { type: 'Nation', label: 'Spain', meta: 'UEFA · FIFA #3 · €1.35bn squad', nationId: 'spain' },
  { type: 'Nation', label: 'France', meta: 'UEFA · FIFA #2 · €1.23bn squad', nationId: 'france' },
  { type: 'Nation', label: 'Türkiye', meta: 'UEFA · FIFA #26 · €0.42bn squad', nationId: 'turkiye' },
  { type: 'Nation', label: 'Brazil', meta: 'CONMEBOL · FIFA #5 · €1.48bn squad', nationId: 'brazil' },
  { type: 'Nation', label: 'Germany', meta: 'UEFA · FIFA #5 · €1.05bn squad', nationId: 'germany' },
  { type: 'Manager', label: 'Pep Guardiola', meta: 'Man City · 4-3-3 · 72.6% win', managerId: 'guardiola' },
  { type: 'Manager', label: 'José Mourinho', meta: 'Fenerbahçe · 4-2-3-1 · 61.8% win', managerId: 'mourinho' },
  { type: 'Manager', label: 'Carlo Ancelotti', meta: 'Real Madrid · UEFA Pro · 64.2% win', managerId: 'ancelotti' },
  { type: 'Manager', label: 'Hansi Flick', meta: 'Barcelona · Gegenpressing · 74.2% win', managerId: 'flick' },
  { type: 'Manager', label: 'Luis Enrique', meta: 'PSG · 4-3-3 · 69.8% win', managerId: 'luis-enrique' },
  { type: 'Manager', label: 'Vincent Kompany', meta: 'Bayern · 4-2-3-1 · 71.0% win', managerId: 'kompany' },
  { type: 'Manager', label: 'Didier Deschamps', meta: 'France NT · UEFA Pro', managerId: 'deschamps' },
]
