/* ------------------------------------------------------------------ */
/*  League / tournament deep profiles (mock)                           */
/* ------------------------------------------------------------------ */

function form(...dots) {
  return dots // 'W' | 'D' | 'L'
}

function row(pos, club, clubId, code, pld, w, d, l, gf, ga, pts, formArr) {
  return {
    pos,
    club,
    clubId: clubId || null,
    code,
    pld,
    w,
    d,
    l,
    gf,
    ga,
    gd: gf - ga,
    pts,
    form: formArr,
  }
}

function allTime(club, clubId, code, seasons, points, titles) {
  return { club, clubId: clubId || null, code, seasons, points, titles }
}

function leader(rank, name, club, code, stat, playerId = null, clubId = null) {
  return { rank, name, club, code, stat, playerId, clubId }
}

function xi(pos, name, club, code, value, x, y, playerId = null, clubId = null, shirt = 10) {
  return { pos, name, club, code, value, x, y, playerId, clubId, shirt }
}

export const LEAGUES_DETAIL = {
  'la-liga': {
    id: 'la-liga',
    name: 'La Liga',
    fullName: 'LaLiga EA Sports',
    code: 'LAL',
    country: 'Spain',
    nationId: 'spain',
    nationCode: 'ESP',
    continent: 'Europe',
    founded: 1929,
    type: 'domestic',
    totalValue: 6.11, // €bn
    teams: 20,
    players: 508,
    foreignersPct: 41,
    avgAge: 26.8,
    zones: {
      ucl: { max: 4, label: 'UEFA Champions League' },
      uel: { min: 5, max: 6, label: 'UEFA Europa League' },
      uecl: { min: 7, max: 7, label: 'UEFA Conference League' },
      relegation: { min: 18, max: 20, label: 'Relegation' },
    },
    standings: [
      row(1, 'FC Barcelona', 'fc-barcelona', 'BAR', 28, 20, 5, 3, 68, 24, 65, form('W', 'W', 'D', 'W', 'W')),
      row(2, 'Real Madrid', 'real-madrid', 'RMA', 28, 19, 5, 4, 62, 28, 62, form('W', 'D', 'W', 'W', 'L')),
      row(3, 'Atlético Madrid', null, 'ATM', 28, 16, 8, 4, 48, 26, 56, form('D', 'W', 'W', 'D', 'W')),
      row(4, 'Athletic Club', null, 'ATH', 28, 14, 8, 6, 42, 28, 50, form('W', 'L', 'W', 'D', 'W')),
      row(5, 'Real Sociedad', null, 'RSO', 28, 12, 9, 7, 38, 32, 45, form('D', 'W', 'L', 'D', 'W')),
      row(6, 'Villarreal', null, 'VIL', 28, 12, 7, 9, 44, 40, 43, form('L', 'W', 'W', 'L', 'D')),
      row(7, 'Real Betis', null, 'BET', 28, 11, 8, 9, 36, 35, 41, form('W', 'D', 'L', 'W', 'D')),
      row(8, 'Sevilla', null, 'SEV', 28, 10, 8, 10, 34, 36, 38, form('L', 'D', 'W', 'L', 'W')),
      row(9, 'Girona', null, 'GIR', 28, 10, 7, 11, 35, 38, 37, form('D', 'L', 'W', 'D', 'L')),
      row(10, 'Celta Vigo', null, 'CEL', 28, 10, 6, 12, 40, 42, 36, form('W', 'L', 'D', 'W', 'L')),
      row(11, 'Osasuna', null, 'OSA', 28, 9, 8, 11, 30, 36, 35, form('D', 'D', 'L', 'W', 'D')),
      row(12, 'Valencia', null, 'VAL', 28, 9, 7, 12, 32, 40, 34, form('L', 'W', 'D', 'L', 'W')),
      row(13, 'Mallorca', null, 'MLL', 28, 8, 9, 11, 28, 34, 33, form('D', 'W', 'L', 'D', 'D')),
      row(14, 'Getafe', null, 'GET', 28, 8, 8, 12, 26, 32, 32, form('L', 'D', 'W', 'L', 'D')),
      row(15, 'Las Palmas', null, 'LPA', 28, 8, 6, 14, 30, 42, 30, form('L', 'L', 'D', 'W', 'L')),
      row(16, 'Alavés', null, 'ALA', 28, 7, 8, 13, 27, 38, 29, form('D', 'L', 'D', 'L', 'W')),
      row(17, 'Rayo Vallecano', null, 'RAY', 28, 7, 7, 14, 28, 40, 28, form('L', 'D', 'L', 'W', 'L')),
      row(18, 'Espanyol', null, 'ESP', 28, 6, 7, 15, 24, 42, 25, form('L', 'L', 'D', 'L', 'W')),
      row(19, 'Valladolid', null, 'VLL', 28, 5, 6, 17, 22, 48, 21, form('L', 'D', 'L', 'L', 'L')),
      row(20, 'Leganés', null, 'LEG', 28, 4, 8, 16, 20, 46, 20, form('D', 'L', 'L', 'D', 'L')),
    ],
    allTime: [
      allTime('Real Madrid', 'real-madrid', 'RMA', 94, 4850, 36),
      allTime('FC Barcelona', 'fc-barcelona', 'BAR', 94, 4720, 27),
      allTime('Atlético Madrid', null, 'ATM', 88, 3680, 11),
      allTime('Athletic Club', null, 'ATH', 94, 3520, 8),
      allTime('Valencia', null, 'VAL', 90, 3100, 6),
      allTime('Sevilla', null, 'SEV', 80, 2680, 1),
      allTime('Real Sociedad', null, 'RSO', 78, 2420, 2),
      allTime('Real Betis', null, 'BET', 58, 1980, 1),
      allTime('Villarreal', null, 'VIL', 25, 1120, 0),
      allTime('Espanyol', null, 'ESP', 86, 2450, 0),
    ],
    leaders: {
      scorers: [
        leader(1, 'Robert Lewandowski', 'Barcelona', 'BAR', 22, null, 'fc-barcelona'),
        leader(2, 'Vinícius Júnior', 'Real Madrid', 'RMA', 18, 'vinicius-junior', 'real-madrid'),
        leader(3, 'Alexander Sørloth', 'Atlético', 'ATM', 16),
        leader(4, 'Raphinha', 'Barcelona', 'BAR', 14, null, 'fc-barcelona'),
        leader(5, 'Ante Budimir', 'Osasuna', 'OSA', 13),
      ],
      assists: [
        leader(1, 'Lamine Yamal', 'Barcelona', 'BAR', 15, 'lamine-yamal', 'fc-barcelona'),
        leader(2, 'Arda Güler', 'Real Madrid', 'RMA', 11, 'arda-guler', 'real-madrid'),
        leader(3, 'Alex Baena', 'Villarreal', 'VIL', 10),
        leader(4, 'Pedri', 'Barcelona', 'BAR', 9, null, 'fc-barcelona'),
        leader(5, 'Vinícius Júnior', 'Real Madrid', 'RMA', 8, 'vinicius-junior', 'real-madrid'),
      ],
      cleanSheets: [
        leader(1, 'Jan Oblak', 'Atlético', 'ATM', 14),
        leader(2, 'Thibaut Courtois', 'Real Madrid', 'RMA', 11, null, 'real-madrid'),
        leader(3, 'Unai Simón', 'Athletic', 'ATH', 10),
        leader(4, 'ter Stegen', 'Barcelona', 'BAR', 9, null, 'fc-barcelona'),
        leader(5, 'Álex Remiro', 'Real Sociedad', 'RSO', 8),
      ],
      cards: [
        leader(1, 'Dani Carvajal', 'Real Madrid', 'RMA', 12, null, 'real-madrid'),
        leader(2, 'Gavi', 'Barcelona', 'BAR', 11, null, 'fc-barcelona'),
        leader(3, 'Dani Parejo', 'Villarreal', 'VIL', 10),
        leader(4, 'Omar Mascarell', 'Mallorca', 'MLL', 10),
        leader(5, 'Sergio Camello', 'Rayo', 'RAY', 9),
      ],
    },
    bestXI: [
      xi('GK', 'Oblak', 'Atlético', 'ATM', 35, 50, 122),
      xi('LB', 'Balde', 'Barcelona', 'BAR', 55, 18, 98, null, 'fc-barcelona', 3),
      xi('CB', 'Cubarsí', 'Barcelona', 'BAR', 50, 38, 102, null, 'fc-barcelona', 2),
      xi('CB', 'Rüdiger', 'Real Madrid', 'RMA', 18, 62, 102, null, 'real-madrid', 22),
      xi('RB', 'Koundé', 'Barcelona', 'BAR', 60, 82, 98, null, 'fc-barcelona', 23),
      xi('CM', 'Bellingham', 'Real Madrid', 'RMA', 180, 32, 70, null, 'real-madrid', 5),
      xi('CM', 'Pedri', 'Barcelona', 'BAR', 100, 50, 72, null, 'fc-barcelona', 8),
      xi('CM', 'Valverde', 'Real Madrid', 'RMA', 120, 68, 70, null, 'real-madrid', 8),
      xi('LW', 'Vinícius', 'Real Madrid', 'RMA', 140, 22, 40, 'vinicius-junior', 'real-madrid', 7),
      xi('ST', 'Lewandowski', 'Barcelona', 'BAR', 12, 50, 28, null, 'fc-barcelona', 9),
      xi('RW', 'Yamal', 'Barcelona', 'BAR', 180, 78, 40, 'lamine-yamal', 'fc-barcelona', 10),
    ],
  },

  'premier-league': {
    id: 'premier-league',
    name: 'Premier League',
    fullName: 'English Premier League',
    code: 'PRL',
    country: 'England',
    nationId: 'england',
    nationCode: 'ENG',
    continent: 'Europe',
    founded: 1992,
    type: 'domestic',
    totalValue: 11.24,
    teams: 20,
    players: 543,
    foreignersPct: 66,
    avgAge: 26.2,
    zones: {
      ucl: { max: 4, label: 'UEFA Champions League' },
      uel: { min: 5, max: 5, label: 'UEFA Europa League' },
      uecl: { min: 6, max: 6, label: 'UEFA Conference League' },
      relegation: { min: 18, max: 20, label: 'Relegation' },
    },
    standings: [
      row(1, 'Liverpool', null, 'LIV', 29, 21, 6, 2, 68, 26, 69, form('W', 'W', 'W', 'D', 'W')),
      row(2, 'Arsenal', null, 'ARS', 29, 19, 8, 2, 62, 24, 65, form('W', 'D', 'W', 'W', 'W')),
      row(3, 'Man City', null, 'MCI', 29, 18, 6, 5, 64, 30, 60, form('W', 'W', 'L', 'W', 'D')),
      row(4, 'Chelsea', null, 'CHE', 29, 16, 7, 6, 55, 34, 55, form('D', 'W', 'W', 'L', 'W')),
      row(5, 'Newcastle', null, 'NEW', 29, 15, 6, 8, 52, 36, 51, form('W', 'L', 'W', 'D', 'W')),
      row(6, 'Aston Villa', null, 'AVL', 29, 14, 7, 8, 48, 38, 49, form('D', 'W', 'L', 'W', 'D')),
      row(7, 'Tottenham', null, 'TOT', 29, 13, 6, 10, 50, 42, 45, form('L', 'W', 'W', 'L', 'W')),
      row(8, 'Man United', null, 'MUN', 29, 12, 7, 10, 42, 40, 43, form('W', 'D', 'L', 'D', 'W')),
      row(9, 'Brighton', null, 'BHA', 29, 11, 9, 9, 44, 42, 42, form('D', 'D', 'W', 'L', 'D')),
      row(10, 'Bournemouth', null, 'BOU', 29, 11, 7, 11, 40, 42, 40, form('W', 'L', 'D', 'W', 'L')),
      row(11, 'Fulham', null, 'FUL', 29, 10, 8, 11, 36, 38, 38, form('D', 'W', 'L', 'D', 'W')),
      row(12, 'Brentford', null, 'BRE', 29, 10, 6, 13, 42, 48, 36, form('L', 'W', 'L', 'W', 'D')),
      row(13, 'Crystal Palace', null, 'CRY', 29, 9, 8, 12, 34, 40, 35, form('D', 'L', 'W', 'D', 'L')),
      row(14, 'West Ham', null, 'WHU', 29, 9, 7, 13, 36, 48, 34, form('L', 'D', 'L', 'W', 'L')),
      row(15, 'Everton', null, 'EVE', 29, 8, 9, 12, 30, 38, 33, form('D', 'D', 'W', 'L', 'D')),
      row(16, 'Wolves', null, 'WOL', 29, 8, 6, 15, 32, 48, 30, form('L', 'W', 'L', 'L', 'D')),
      row(17, 'Nottm Forest', null, 'NFO', 29, 7, 8, 14, 28, 42, 29, form('D', 'L', 'D', 'L', 'W')),
      row(18, 'Leicester', null, 'LEI', 29, 5, 7, 17, 26, 52, 22, form('L', 'L', 'D', 'L', 'L')),
      row(19, 'Ipswich', null, 'IPS', 29, 4, 8, 17, 24, 54, 20, form('L', 'D', 'L', 'D', 'L')),
      row(20, 'Southampton', null, 'SOU', 29, 3, 5, 21, 22, 62, 14, form('L', 'L', 'L', 'D', 'L')),
    ],
    allTime: [
      allTime('Man United', null, 'MUN', 33, 2680, 13),
      allTime('Arsenal', null, 'ARS', 33, 2450, 3),
      allTime('Chelsea', null, 'CHE', 33, 2380, 5),
      allTime('Liverpool', null, 'LIV', 33, 2420, 2),
      allTime('Man City', null, 'MCI', 28, 1980, 8),
      allTime('Tottenham', null, 'TOT', 33, 1880, 0),
      allTime('Everton', null, 'EVE', 33, 1620, 0),
      allTime('Newcastle', null, 'NEW', 30, 1480, 0),
    ],
    leaders: {
      scorers: [
        leader(1, 'Erling Haaland', 'Man City', 'MCI', 24),
        leader(2, 'Mohamed Salah', 'Liverpool', 'LIV', 22),
        leader(3, 'Alexander Isak', 'Newcastle', 'NEW', 19),
        leader(4, 'Cole Palmer', 'Chelsea', 'CHE', 16),
        leader(5, 'Bukayo Saka', 'Arsenal', 'ARS', 14),
      ],
      assists: [
        leader(1, 'Mohamed Salah', 'Liverpool', 'LIV', 14),
        leader(2, 'Bruno Fernandes', 'Man United', 'MUN', 11),
        leader(3, 'Bukayo Saka', 'Arsenal', 'ARS', 10),
        leader(4, 'Kevin De Bruyne', 'Man City', 'MCI', 9),
        leader(5, 'Cole Palmer', 'Chelsea', 'CHE', 9),
      ],
      cleanSheets: [
        leader(1, 'Alisson', 'Liverpool', 'LIV', 13),
        leader(2, 'David Raya', 'Arsenal', 'ARS', 12),
        leader(3, 'Ederson', 'Man City', 'MCI', 10),
        leader(4, 'Nick Pope', 'Newcastle', 'NEW', 9),
        leader(5, 'Robert Sánchez', 'Chelsea', 'CHE', 8),
      ],
      cards: [
        leader(1, 'João Palhinha', 'Bayern*', 'FCB', 11),
        leader(2, 'Yves Bissouma', 'Tottenham', 'TOT', 10),
        leader(3, 'Casemiro', 'Man United', 'MUN', 10),
        leader(4, 'Moises Caicedo', 'Chelsea', 'CHE', 9),
        leader(5, 'Declan Rice', 'Arsenal', 'ARS', 8),
      ],
    },
    bestXI: [
      xi('GK', 'Alisson', 'Liverpool', 'LIV', 45, 50, 122),
      xi('LB', 'Robertson', 'Liverpool', 'LIV', 30, 18, 98),
      xi('CB', 'Saliba', 'Arsenal', 'ARS', 80, 38, 102),
      xi('CB', 'van Dijk', 'Liverpool', 'LIV', 35, 62, 102),
      xi('RB', 'Alexander-Arnold', 'Liverpool', 'LIV', 70, 82, 98),
      xi('CM', 'Rodri', 'Man City', 'MCI', 100, 32, 70),
      xi('CM', 'Rice', 'Arsenal', 'ARS', 110, 50, 72),
      xi('CM', 'Palmer', 'Chelsea', 'CHE', 100, 68, 70),
      xi('LW', 'Salah', 'Liverpool', 'LIV', 80, 22, 40),
      xi('ST', 'Haaland', 'Man City', 'MCI', 180, 50, 28),
      xi('RW', 'Saka', 'Arsenal', 'ARS', 120, 78, 40),
    ],
  },

  bundesliga: {
    id: 'bundesliga',
    name: 'Bundesliga',
    fullName: 'Bundesliga',
    code: 'BUN',
    country: 'Germany',
    nationId: 'germany',
    nationCode: 'GER',
    continent: 'Europe',
    founded: 1963,
    type: 'domestic',
    totalValue: 4.02,
    teams: 18,
    players: 486,
    foreignersPct: 52,
    avgAge: 25.9,
    zones: {
      ucl: { max: 4, label: 'UEFA Champions League' },
      uel: { min: 5, max: 5, label: 'UEFA Europa League' },
      uecl: { min: 6, max: 6, label: 'UEFA Conference League' },
      relegation: { min: 16, max: 18, label: 'Relegation / Play-off' },
    },
    standings: [
      row(1, 'Bayern Munich', 'bayern-munich', 'FCB', 26, 20, 4, 2, 78, 22, 64, form('W', 'W', 'W', 'D', 'W')),
      row(2, 'Leverkusen', null, 'B04', 26, 16, 6, 4, 58, 28, 54, form('W', 'D', 'W', 'L', 'W')),
      row(3, 'Dortmund', null, 'BVB', 26, 14, 6, 6, 52, 34, 48, form('L', 'W', 'W', 'D', 'W')),
      row(4, 'RB Leipzig', null, 'RBL', 26, 13, 7, 6, 48, 32, 46, form('D', 'W', 'L', 'W', 'D')),
      row(5, 'Frankfurt', null, 'SGE', 26, 12, 7, 7, 44, 36, 43, form('W', 'L', 'D', 'W', 'W')),
      row(6, 'Freiburg', null, 'SCF', 26, 11, 7, 8, 38, 36, 40, form('D', 'W', 'L', 'D', 'W')),
      row(7, 'Wolfsburg', null, 'WOB', 26, 10, 7, 9, 40, 38, 37, form('L', 'W', 'D', 'W', 'L')),
      row(8, 'Stuttgart', null, 'VFB', 26, 10, 6, 10, 42, 40, 36, form('W', 'L', 'W', 'L', 'D')),
      row(9, 'Gladbach', null, 'BMG', 26, 9, 7, 10, 36, 40, 34, form('D', 'L', 'W', 'D', 'L')),
      row(10, 'Hoffenheim', null, 'TSG', 26, 9, 6, 11, 38, 44, 33, form('L', 'D', 'L', 'W', 'D')),
      row(11, 'Mainz', null, 'M05', 26, 8, 8, 10, 34, 38, 32, form('D', 'W', 'L', 'D', 'W')),
      row(12, 'Augsburg', null, 'FCA', 26, 8, 7, 11, 30, 40, 31, form('L', 'D', 'W', 'L', 'D')),
      row(13, 'Werder', null, 'SVW', 26, 7, 8, 11, 32, 42, 29, form('D', 'L', 'D', 'W', 'L')),
      row(14, 'Union Berlin', null, 'FCU', 26, 7, 7, 12, 28, 40, 28, form('L', 'D', 'L', 'D', 'W')),
      row(15, 'Heidenheim', null, 'FCH', 26, 6, 7, 13, 26, 42, 25, form('L', 'L', 'D', 'L', 'W')),
      row(16, 'Bochum', null, 'BOC', 26, 5, 7, 14, 24, 48, 22, form('D', 'L', 'L', 'D', 'L')),
      row(17, 'St. Pauli', null, 'STP', 26, 4, 7, 15, 22, 46, 19, form('L', 'D', 'L', 'L', 'D')),
      row(18, 'Holstein Kiel', null, 'KIE', 26, 3, 6, 17, 20, 54, 15, form('L', 'L', 'D', 'L', 'L')),
    ],
    allTime: [
      allTime('Bayern Munich', 'bayern-munich', 'FCB', 61, 3980, 33),
      allTime('Dortmund', null, 'BVB', 58, 2680, 5),
      allTime('Gladbach', null, 'BMG', 57, 2280, 5),
      allTime('Werder', null, 'SVW', 58, 2420, 4),
      allTime('Hamburg', null, 'HSV', 55, 2180, 3),
      allTime('Stuttgart', null, 'VFB', 56, 2120, 3),
      allTime('Frankfurt', null, 'SGE', 56, 2080, 1),
      allTime('Schalke', null, 'S04', 54, 1980, 0),
    ],
    leaders: {
      scorers: [
        leader(1, 'Harry Kane', 'Bayern', 'FCB', 26, null, 'bayern-munich'),
        leader(2, 'Serhou Guirassy', 'Dortmund', 'BVB', 18),
        leader(3, 'Omar Marmoush', 'Frankfurt', 'SGE', 16),
        leader(4, 'Michael Olise', 'Bayern', 'FCB', 13, 'michael-olise', 'bayern-munich'),
        leader(5, 'Florian Wirtz', 'Leverkusen', 'B04', 12),
      ],
      assists: [
        leader(1, 'Jamal Musiala', 'Bayern', 'FCB', 12, 'jamal-musiala', 'bayern-munich'),
        leader(2, 'Florian Wirtz', 'Leverkusen', 'B04', 11),
        leader(3, 'Michael Olise', 'Bayern', 'FCB', 10, 'michael-olise', 'bayern-munich'),
        leader(4, 'Xavi Simons', 'Leipzig', 'RBL', 9),
        leader(5, 'Julian Brandt', 'Dortmund', 'BVB', 8),
      ],
      cleanSheets: [
        leader(1, 'Manuel Neuer', 'Bayern', 'FCB', 11, null, 'bayern-munich'),
        leader(2, 'Gregor Kobel', 'Dortmund', 'BVB', 9),
        leader(3, 'Péter Gulácsi', 'Leipzig', 'RBL', 8),
        leader(4, 'Lukáš Hrádecký', 'Leverkusen', 'B04', 7),
        leader(5, 'Kevin Trapp', 'Frankfurt', 'SGE', 7),
      ],
      cards: [
        leader(1, 'Jonathan Tah', 'Leverkusen', 'B04', 9),
        leader(2, 'Emre Can', 'Dortmund', 'BVB', 8),
        leader(3, 'Granit Xhaka', 'Leverkusen', 'B04', 8),
        leader(4, 'Dayot Upamecano', 'Bayern', 'FCB', 7, null, 'bayern-munich'),
        leader(5, 'Willi Orbán', 'Leipzig', 'RBL', 7),
      ],
    },
    bestXI: [
      xi('GK', 'Neuer', 'Bayern', 'FCB', 4, 50, 122, null, 'bayern-munich', 1),
      xi('LB', 'Davies', 'Bayern', 'FCB', 50, 18, 98, null, 'bayern-munich', 19),
      xi('CB', 'Kim', 'Bayern', 'FCB', 40, 38, 102, null, 'bayern-munich', 3),
      xi('CB', 'Schlotterbeck', 'Dortmund', 'BVB', 45, 62, 102),
      xi('RB', 'Kimmich', 'Bayern', 'FCB', 45, 82, 98, null, 'bayern-munich', 6),
      xi('CM', 'Wirtz', 'Leverkusen', 'B04', 130, 32, 70),
      xi('CM', 'Pavlović', 'Bayern', 'FCB', 45, 50, 72, null, 'bayern-munich', 45),
      xi('CM', 'Musiala', 'Bayern', 'FCB', 125, 68, 70, 'jamal-musiala', 'bayern-munich', 42),
      xi('LW', 'Sané', 'Bayern', 'FCB', 40, 22, 40, null, 'bayern-munich', 10),
      xi('ST', 'Kane', 'Bayern', 'FCB', 80, 50, 28, null, 'bayern-munich', 9),
      xi('RW', 'Olise', 'Bayern', 'FCB', 110, 78, 40, 'michael-olise', 'bayern-munich', 17),
    ],
  },

  'serie-a': {
    id: 'serie-a',
    name: 'Serie A',
    fullName: 'Serie A Enilive',
    code: 'SEA',
    country: 'Italy',
    nationId: 'italy',
    nationCode: 'ITA',
    continent: 'Europe',
    founded: 1898,
    type: 'domestic',
    totalValue: 4.87,
    teams: 20,
    players: 561,
    foreignersPct: 61,
    avgAge: 26.5,
    zones: {
      ucl: { max: 4, label: 'UEFA Champions League' },
      uel: { min: 5, max: 5, label: 'UEFA Europa League' },
      uecl: { min: 6, max: 6, label: 'UEFA Conference League' },
      relegation: { min: 18, max: 20, label: 'Relegation' },
    },
    standings: [
      row(1, 'Inter', null, 'INT', 28, 19, 6, 3, 58, 22, 63, form('W', 'W', 'D', 'W', 'W')),
      row(2, 'Napoli', null, 'NAP', 28, 18, 6, 4, 52, 24, 60, form('W', 'D', 'W', 'W', 'L')),
      row(3, 'Atalanta', null, 'ATA', 28, 16, 7, 5, 55, 28, 55, form('D', 'W', 'W', 'L', 'W')),
      row(4, 'Juventus', 'juventus', 'JUV', 28, 15, 9, 4, 46, 26, 54, form('W', 'D', 'W', 'D', 'W')),
      row(5, 'Milan', null, 'MIL', 28, 14, 8, 6, 48, 32, 50, form('L', 'W', 'W', 'D', 'W')),
      row(6, 'Lazio', null, 'LAZ', 28, 13, 6, 9, 42, 34, 45, form('W', 'L', 'D', 'W', 'W')),
      row(7, 'Fiorentina', null, 'FIO', 28, 12, 7, 9, 40, 34, 43, form('D', 'W', 'L', 'W', 'D')),
      row(8, 'Roma', null, 'ROM', 28, 11, 8, 9, 38, 34, 41, form('W', 'D', 'L', 'D', 'W')),
      row(9, 'Bologna', null, 'BOL', 28, 10, 9, 9, 36, 34, 39, form('D', 'L', 'W', 'D', 'D')),
      row(10, 'Torino', null, 'TOR', 28, 9, 10, 9, 32, 32, 37, form('D', 'D', 'L', 'W', 'D')),
      row(11, 'Udinese', null, 'UDI', 28, 9, 7, 12, 30, 38, 34, form('L', 'W', 'D', 'L', 'W')),
      row(12, 'Genoa', null, 'GEN', 28, 8, 9, 11, 28, 36, 33, form('D', 'L', 'D', 'W', 'L')),
      row(13, 'Monza', null, 'MON', 28, 8, 7, 13, 30, 40, 31, form('L', 'D', 'W', 'L', 'D')),
      row(14, 'Cagliari', null, 'CAG', 28, 7, 8, 13, 28, 42, 29, form('D', 'L', 'L', 'W', 'D')),
      row(15, 'Lecce', null, 'LEC', 28, 7, 7, 14, 26, 40, 28, form('L', 'D', 'L', 'D', 'W')),
      row(16, 'Empoli', null, 'EMP', 28, 6, 9, 13, 24, 38, 27, form('D', 'D', 'L', 'L', 'D')),
      row(17, 'Hellas Verona', null, 'VER', 28, 6, 7, 15, 26, 44, 25, form('L', 'L', 'D', 'W', 'L')),
      row(18, 'Como', null, 'COM', 28, 5, 8, 15, 24, 42, 23, form('D', 'L', 'L', 'D', 'L')),
      row(19, 'Parma', null, 'PAR', 28, 5, 7, 16, 26, 48, 22, form('L', 'D', 'L', 'L', 'W')),
      row(20, 'Venezia', null, 'VEN', 28, 4, 6, 18, 22, 50, 18, form('L', 'L', 'D', 'L', 'L')),
    ],
    allTime: [
      allTime('Juventus', 'juventus', 'JUV', 92, 4280, 36),
      allTime('Inter', null, 'INT', 93, 3980, 20),
      allTime('Milan', null, 'MIL', 91, 3920, 19),
      allTime('Roma', null, 'ROM', 92, 3120, 3),
      allTime('Napoli', null, 'NAP', 79, 2680, 4),
      allTime('Lazio', null, 'LAZ', 82, 2580, 2),
      allTime('Fiorentina', null, 'FIO', 87, 2520, 2),
      allTime('Torino', null, 'TOR', 81, 2280, 7),
    ],
    leaders: {
      scorers: [
        leader(1, 'Lautaro Martínez', 'Inter', 'INT', 20),
        leader(2, 'Dušan Vlahović', 'Juventus', 'JUV', 16, null, 'juventus'),
        leader(3, 'Romelu Lukaku', 'Napoli', 'NAP', 15),
        leader(4, 'Kenan Yıldız', 'Juventus', 'JUV', 12, 'kenan-yildiz', 'juventus'),
        leader(5, 'Ademola Lookman', 'Atalanta', 'ATA', 12),
      ],
      assists: [
        leader(1, 'Kenan Yıldız', 'Juventus', 'JUV', 10, 'kenan-yildiz', 'juventus'),
        leader(2, 'Khvicha Kvaratskhelia', 'Napoli', 'NAP', 9),
        leader(3, 'Nicolò Barella', 'Inter', 'INT', 8),
        leader(4, 'Rafael Leão', 'Milan', 'MIL', 8),
        leader(5, 'Paulo Dybala', 'Roma', 'ROM', 7),
      ],
      cleanSheets: [
        leader(1, 'Yann Sommer', 'Inter', 'INT', 13),
        leader(2, 'Michele Di Gregorio', 'Juventus', 'JUV', 11, null, 'juventus'),
        leader(3, 'Alex Meret', 'Napoli', 'NAP', 10),
        leader(4, 'Mike Maignan', 'Milan', 'MIL', 9),
        leader(5, 'Mile Svilar', 'Roma', 'ROM', 8),
      ],
      cards: [
        leader(1, 'Manuel Locatelli', 'Juventus', 'JUV', 10, null, 'juventus'),
        leader(2, 'Hakan Çalhanoğlu', 'Inter', 'INT', 9),
        leader(3, 'Stanislav Lobotka', 'Napoli', 'NAP', 8),
        leader(4, 'Teun Koopmeiners', 'Juventus', 'JUV', 8, null, 'juventus'),
        leader(5, 'Ismaël Bennacer', 'Milan', 'MIL', 7),
      ],
    },
    bestXI: [
      xi('GK', 'Sommer', 'Inter', 'INT', 12, 50, 122),
      xi('LB', 'Dimarco', 'Inter', 'INT', 40, 18, 98),
      xi('CB', 'Bremer', 'Juventus', 'JUV', 55, 38, 102, null, 'juventus', 3),
      xi('CB', 'Bastoni', 'Inter', 'INT', 70, 62, 102),
      xi('RB', 'Di Lorenzo', 'Napoli', 'NAP', 30, 82, 98),
      xi('CM', 'Barella', 'Inter', 'INT', 70, 32, 70),
      xi('CM', 'Çalhanoğlu', 'Inter', 'INT', 40, 50, 72),
      xi('CM', 'Yıldız', 'Juventus', 'JUV', 75, 68, 70, 'kenan-yildiz', 'juventus', 10),
      xi('LW', 'Leão', 'Milan', 'MIL', 80, 22, 40),
      xi('ST', 'Lautaro', 'Inter', 'INT', 100, 50, 28),
      xi('RW', 'Lookman', 'Atalanta', 'ATA', 55, 78, 40),
    ],
  },

  'ligue-1': {
    id: 'ligue-1',
    name: 'Ligue 1',
    fullName: 'Ligue 1 McDonald’s',
    code: 'LI1',
    country: 'France',
    nationId: 'france',
    nationCode: 'FRA',
    continent: 'Europe',
    founded: 1932,
    type: 'domestic',
    totalValue: 3.55,
    teams: 18,
    players: 472,
    foreignersPct: 48,
    avgAge: 25.1,
    zones: {
      ucl: { max: 3, label: 'UEFA Champions League' },
      uel: { min: 4, max: 4, label: 'UEFA Europa League' },
      uecl: { min: 5, max: 5, label: 'UEFA Conference League' },
      relegation: { min: 16, max: 18, label: 'Relegation / Play-off' },
    },
    standings: [
      row(1, 'Paris SG', 'psg', 'PSG', 26, 21, 4, 1, 72, 20, 67, form('W', 'W', 'W', 'W', 'D')),
      row(2, 'Monaco', null, 'ASM', 26, 15, 6, 5, 52, 30, 51, form('W', 'D', 'L', 'W', 'W')),
      row(3, 'Marseille', null, 'OM', 26, 14, 6, 6, 48, 32, 48, form('L', 'W', 'W', 'D', 'W')),
      row(4, 'Lille', null, 'LIL', 26, 13, 7, 6, 42, 28, 46, form('D', 'W', 'W', 'L', 'D')),
      row(5, 'Lyon', null, 'OL', 26, 12, 6, 8, 44, 36, 42, form('W', 'L', 'D', 'W', 'W')),
      row(6, 'Nice', null, 'NIC', 26, 11, 8, 7, 38, 30, 41, form('D', 'W', 'D', 'L', 'W')),
      row(7, 'Lens', null, 'RCL', 26, 11, 6, 9, 36, 32, 39, form('W', 'L', 'W', 'D', 'L')),
      row(8, 'Rennes', null, 'REN', 26, 10, 6, 10, 38, 36, 36, form('L', 'W', 'D', 'W', 'L')),
      row(9, 'Strasbourg', null, 'RCS', 26, 9, 7, 10, 34, 36, 34, form('D', 'L', 'W', 'D', 'W')),
      row(10, 'Toulouse', null, 'TFC', 26, 9, 6, 11, 32, 36, 33, form('L', 'D', 'W', 'L', 'D')),
      row(11, 'Brest', null, 'SB29', 26, 9, 5, 12, 30, 38, 32, form('W', 'L', 'L', 'D', 'W')),
      row(12, 'Reims', null, 'SDR', 26, 8, 7, 11, 30, 36, 31, form('D', 'D', 'L', 'W', 'L')),
      row(13, 'Nantes', null, 'FCN', 26, 7, 8, 11, 28, 38, 29, form('L', 'D', 'D', 'L', 'W')),
      row(14, 'Auxerre', null, 'AJA', 26, 7, 6, 13, 28, 42, 27, form('L', 'W', 'L', 'D', 'L')),
      row(15, 'Angers', null, 'SCO', 26, 6, 7, 13, 26, 40, 25, form('D', 'L', 'L', 'W', 'D')),
      row(16, 'Le Havre', null, 'HAC', 26, 6, 5, 15, 24, 44, 23, form('L', 'L', 'D', 'L', 'W')),
      row(17, 'Saint-Étienne', null, 'ASSE', 26, 5, 6, 15, 22, 46, 21, form('L', 'D', 'L', 'L', 'D')),
      row(18, 'Montpellier', null, 'MHSC', 26, 4, 5, 17, 20, 50, 17, form('L', 'L', 'D', 'L', 'L')),
    ],
    allTime: [
      allTime('Paris SG', 'psg', 'PSG', 52, 2980, 12),
      allTime('Saint-Étienne', null, 'ASSE', 69, 2680, 10),
      allTime('Marseille', null, 'OM', 75, 2880, 9),
      allTime('Nantes', null, 'FCN', 56, 2280, 8),
      allTime('Monaco', null, 'ASM', 66, 2480, 8),
      allTime('Lyon', null, 'OL', 66, 2520, 7),
      allTime('Bordeaux', null, 'FCGB', 69, 2380, 6),
      allTime('Reims', null, 'SDR', 38, 1480, 6),
    ],
    leaders: {
      scorers: [
        leader(1, 'Bradley Barcola', 'PSG', 'PSG', 16, null, 'psg'),
        leader(2, 'Wissam Ben Yedder', 'Monaco', 'ASM', 14),
        leader(3, 'Gonçalo Ramos', 'PSG', 'PSG', 13, null, 'psg'),
        leader(4, 'Jonathan David', 'Lille', 'LIL', 12),
        leader(5, 'Désiré Doué', 'PSG', 'PSG', 11, 'desire-doue', 'psg'),
      ],
      assists: [
        leader(1, 'Ousmane Dembélé', 'PSG', 'PSG', 12, null, 'psg'),
        leader(2, 'Désiré Doué', 'PSG', 'PSG', 11, 'desire-doue', 'psg'),
        leader(3, 'Vitinha', 'PSG', 'PSG', 9, null, 'psg'),
        leader(4, 'Takumi Minamino', 'Monaco', 'ASM', 8),
        leader(5, 'Pierre-Emile Højbjerg', 'Marseille', 'OM', 7),
      ],
      cleanSheets: [
        leader(1, 'Gianluigi Donnarumma', 'PSG', 'PSG', 12, null, 'psg'),
        leader(2, 'Lucas Chevalier', 'Lille', 'LIL', 9),
        leader(3, 'Radosław Majecki', 'Monaco', 'ASM', 8),
        leader(4, 'Geronimo Rulli', 'Marseille', 'OM', 7),
        leader(5, 'Lucas Perri', 'Lyon', 'OL', 7),
      ],
      cards: [
        leader(1, 'Nuno Mendes', 'PSG', 'PSG', 8, null, 'psg'),
        leader(2, 'Denis Zakaria', 'Monaco', 'ASM', 8),
        leader(3, 'João Neves', 'PSG', 'PSG', 7, null, 'psg'),
        leader(4, 'Pierre Højbjerg', 'Marseille', 'OM', 7),
        leader(5, 'Benjamin André', 'Lille', 'LIL', 6),
      ],
    },
    bestXI: [
      xi('GK', 'Donnarumma', 'PSG', 'PSG', 50, 50, 122, null, 'psg', 1),
      xi('LB', 'Mendes', 'PSG', 'PSG', 50, 18, 98, null, 'psg', 25),
      xi('CB', 'Pacho', 'PSG', 'PSG', 40, 38, 102, null, 'psg', 51),
      xi('CB', 'Marquinhos', 'PSG', 'PSG', 40, 62, 102, null, 'psg', 5),
      xi('RB', 'Hakimi', 'PSG', 'PSG', 55, 82, 98, null, 'psg', 2),
      xi('CM', 'Neves', 'PSG', 'PSG', 70, 32, 70, null, 'psg', 87),
      xi('CM', 'Vitinha', 'PSG', 'PSG', 70, 50, 72, null, 'psg', 17),
      xi('CM', 'Doué', 'PSG', 'PSG', 90, 68, 70, 'desire-doue', 'psg', 14),
      xi('LW', 'Kvaratskhelia', 'PSG', 'PSG', 80, 22, 40, null, 'psg', 7),
      xi('ST', 'Ramos', 'PSG', 'PSG', 45, 50, 28, null, 'psg', 9),
      xi('RW', 'Dembélé', 'PSG', 'PSG', 70, 78, 40, null, 'psg', 10),
    ],
  },

  'super-lig': {
    id: 'super-lig',
    name: 'Trendyol Süper Lig',
    fullName: 'Trendyol Süper Lig',
    code: 'SÜP',
    country: 'Türkiye',
    nationId: 'turkiye',
    nationCode: 'TUR',
    continent: 'Europe',
    founded: 1959,
    type: 'domestic',
    totalValue: 1.12,
    teams: 19,
    players: 512,
    foreignersPct: 44,
    avgAge: 26.9,
    zones: {
      ucl: { max: 2, label: 'UEFA Champions League' },
      uel: { min: 3, max: 3, label: 'UEFA Europa League' },
      uecl: { min: 4, max: 4, label: 'UEFA Conference League' },
      relegation: { min: 17, max: 19, label: 'Relegation' },
    },
    standings: [
      row(1, 'Galatasaray', null, 'GS', 28, 22, 4, 2, 68, 24, 70, form('W', 'W', 'W', 'D', 'W')),
      row(2, 'Fenerbahçe', null, 'FB', 28, 20, 5, 3, 64, 26, 65, form('W', 'D', 'W', 'W', 'W')),
      row(3, 'Beşiktaş', null, 'BJK', 28, 16, 6, 6, 48, 30, 54, form('W', 'L', 'W', 'D', 'W')),
      row(4, 'Trabzonspor', null, 'TS', 28, 14, 7, 7, 46, 32, 49, form('D', 'W', 'L', 'W', 'D')),
      row(5, 'Başakşehir', null, 'IBFK', 28, 12, 8, 8, 40, 34, 44, form('W', 'D', 'W', 'L', 'D')),
      row(6, 'Samsunspor', null, 'SAM', 28, 12, 6, 10, 38, 36, 42, form('L', 'W', 'D', 'W', 'L')),
      row(7, 'Eyüpspor', null, 'EYÜ', 28, 11, 7, 10, 36, 36, 40, form('D', 'L', 'W', 'D', 'W')),
      row(8, 'Göztepe', null, 'GÖZ', 28, 10, 8, 10, 34, 34, 38, form('W', 'D', 'L', 'D', 'W')),
      row(9, 'Kasımpaşa', null, 'KAS', 28, 10, 7, 11, 40, 42, 37, form('L', 'W', 'D', 'L', 'W')),
      row(10, 'Antalyaspor', null, 'ANT', 28, 9, 8, 11, 32, 38, 35, form('D', 'L', 'D', 'W', 'L')),
      row(11, 'Konyaspor', null, 'KON', 28, 9, 7, 12, 30, 38, 34, form('L', 'D', 'W', 'L', 'D')),
      row(12, 'Rizespor', null, 'ÇAY', 28, 9, 6, 13, 32, 42, 33, form('W', 'L', 'L', 'D', 'W')),
      row(13, 'Alanyaspor', null, 'ALA', 28, 8, 8, 12, 34, 42, 32, form('D', 'W', 'L', 'D', 'L')),
      row(14, 'Sivasspor', null, 'SİV', 28, 8, 7, 13, 30, 40, 31, form('L', 'D', 'L', 'W', 'D')),
      row(15, 'Kayserispor', null, 'KAY', 28, 7, 8, 13, 28, 42, 29, form('D', 'L', 'D', 'L', 'W')),
      row(16, 'Bodrum FK', null, 'BOD', 28, 7, 6, 15, 26, 44, 27, form('L', 'L', 'W', 'L', 'D')),
      row(17, 'Hatayspor', null, 'HAT', 28, 5, 7, 16, 24, 48, 22, form('L', 'D', 'L', 'L', 'D')),
      row(18, 'Adana Demirspor', null, 'ADS', 28, 4, 6, 18, 22, 54, 18, form('L', 'L', 'D', 'L', 'L')),
      row(19, 'Gaziantep FK', null, 'GFK', 28, 4, 5, 19, 20, 52, 17, form('L', 'D', 'L', 'L', 'L')),
    ],
    allTime: [
      allTime('Fenerbahçe', null, 'FB', 67, 4120, 19),
      allTime('Galatasaray', null, 'GS', 67, 4080, 24),
      allTime('Beşiktaş', null, 'BJK', 67, 3780, 16),
      allTime('Trabzonspor', null, 'TS', 51, 2680, 7),
      allTime('Bursaspor', null, 'BUR', 48, 1680, 1),
      allTime('Başakşehir', null, 'IBFK', 18, 920, 1),
      allTime('Sivasspor', null, 'SİV', 22, 880, 0),
      allTime('Antalyaspor', null, 'ANT', 30, 980, 0),
    ],
    leaders: {
      scorers: [
        leader(1, 'Victor Osimhen', 'Galatasaray', 'GS', 24),
        leader(2, 'Edin Džeko', 'Fenerbahçe', 'FB', 18),
        leader(3, 'Ciro Immobile', 'Beşiktaş', 'BJK', 14),
        leader(4, 'Mauro Icardi', 'Galatasaray', 'GS', 13),
        leader(5, 'Youssef En-Nesyri', 'Fenerbahçe', 'FB', 12),
      ],
      assists: [
        leader(1, 'Dries Mertens', 'Galatasaray', 'GS', 11),
        leader(2, 'Dusan Tadic', 'Fenerbahçe', 'FB', 10),
        leader(3, 'Rafa Silva', 'Beşiktaş', 'BJK', 9),
        leader(4, 'Barış Alper Yılmaz', 'Galatasaray', 'GS', 8),
        leader(5, 'Fred', 'Fenerbahçe', 'FB', 7),
      ],
      cleanSheets: [
        leader(1, 'Fernando Muslera', 'Galatasaray', 'GS', 12),
        leader(2, 'Dominik Livaković', 'Fenerbahçe', 'FB', 10),
        leader(3, 'Mert Günok', 'Beşiktaş', 'BJK', 8),
        leader(4, 'Uğurcan Çakır', 'Trabzonspor', 'TS', 7),
        leader(5, 'Volkan Babacan', 'Başakşehir', 'IBFK', 6),
      ],
      cards: [
        leader(1, 'Fred', 'Fenerbahçe', 'FB', 11),
        leader(2, 'Lucas Torreira', 'Galatasaray', 'GS', 10),
        leader(3, 'Gedson Fernandes', 'Beşiktaş', 'BJK', 9),
        leader(4, 'Salih Özcan', 'Trabzonspor', 'TS', 8),
        leader(5, 'Berkan Kutlu', 'Galatasaray', 'GS', 8),
      ],
    },
    bestXI: [
      xi('GK', 'Muslera', 'Galatasaray', 'GS', 2, 50, 122),
      xi('LB', 'Köhn', 'Galatasaray', 'GS', 12, 18, 98),
      xi('CB', 'Abdulkerim', 'Galatasaray', 'GS', 15, 38, 102),
      xi('CB', 'Djiku', 'Fenerbahçe', 'FB', 14, 62, 102),
      xi('RB', 'Boey', 'Galatasaray', 'GS', 25, 82, 98),
      xi('CM', 'Torreira', 'Galatasaray', 'GS', 18, 32, 70),
      xi('CM', 'Fred', 'Fenerbahçe', 'FB', 20, 50, 72),
      xi('CM', 'Sara', 'Galatasaray', 'GS', 22, 68, 70),
      xi('LW', 'Barış Alper', 'Galatasaray', 'GS', 30, 22, 40),
      xi('ST', 'Osimhen', 'Galatasaray', 'GS', 90, 50, 28),
      xi('RW', 'Tadic', 'Fenerbahçe', 'FB', 12, 78, 40),
    ],
  },

  ucl: {
    id: 'ucl',
    name: 'UEFA Champions League',
    fullName: 'UEFA Champions League',
    code: 'UCL',
    country: 'Europe',
    nationId: 'uefa',
    nationCode: 'EUR',
    continent: 'Europe',
    founded: 1955,
    type: 'international',
    totalValue: 18.4,
    teams: 36,
    players: 900,
    foreignersPct: 72,
    avgAge: 26.1,
    zones: {
      ucl: { max: 8, label: 'Round of 16 (direct)' },
      uel: { min: 9, max: 24, label: 'Play-off round' },
      relegation: { min: 25, max: 36, label: 'Eliminated' },
    },
    standings: [
      row(1, 'Liverpool', null, 'LIV', 8, 7, 1, 0, 22, 6, 22, form('W', 'W', 'W', 'D', 'W')),
      row(2, 'Barcelona', 'fc-barcelona', 'BAR', 8, 6, 2, 0, 24, 8, 20, form('W', 'W', 'D', 'W', 'W')),
      row(3, 'Arsenal', null, 'ARS', 8, 6, 1, 1, 18, 6, 19, form('W', 'W', 'L', 'W', 'W')),
      row(4, 'Inter', null, 'INT', 8, 6, 1, 1, 16, 6, 19, form('W', 'D', 'W', 'W', 'W')),
      row(5, 'Bayern', 'bayern-munich', 'FCB', 8, 5, 2, 1, 20, 10, 17, form('W', 'D', 'W', 'W', 'L')),
      row(6, 'Real Madrid', 'real-madrid', 'RMA', 8, 5, 1, 2, 18, 12, 16, form('W', 'L', 'W', 'W', 'D')),
      row(7, 'Atalanta', null, 'ATA', 8, 4, 3, 1, 16, 10, 15, form('D', 'W', 'D', 'W', 'W')),
      row(8, 'Leverkusen', null, 'B04', 8, 4, 2, 2, 14, 10, 14, form('W', 'L', 'W', 'D', 'W')),
      row(9, 'PSG', 'psg', 'PSG', 8, 4, 2, 2, 16, 12, 14, form('W', 'D', 'L', 'W', 'W')),
      row(10, 'Atlético', null, 'ATM', 8, 4, 1, 3, 12, 10, 13, form('L', 'W', 'W', 'L', 'W')),
      row(11, 'Dortmund', null, 'BVB', 8, 4, 1, 3, 14, 12, 13, form('W', 'L', 'W', 'D', 'L')),
      row(12, 'Milan', null, 'MIL', 8, 3, 3, 2, 12, 10, 12, form('D', 'W', 'D', 'L', 'W')),
      row(13, 'Juventus', 'juventus', 'JUV', 8, 3, 2, 3, 10, 10, 11, form('D', 'L', 'W', 'D', 'W')),
      row(14, 'Benfica', null, 'SLB', 8, 3, 2, 3, 12, 12, 11, form('W', 'L', 'D', 'W', 'L')),
      row(15, 'Sporting', null, 'SCP', 8, 3, 1, 4, 12, 14, 10, form('L', 'W', 'L', 'W', 'D')),
      row(16, 'Monaco', null, 'ASM', 8, 3, 1, 4, 10, 14, 10, form('L', 'W', 'L', 'D', 'W')),
      row(17, 'Aston Villa', null, 'AVL', 8, 2, 3, 3, 10, 12, 9, form('D', 'L', 'W', 'D', 'L')),
      row(18, 'Celtic', null, 'CEL', 8, 2, 2, 4, 10, 16, 8, form('L', 'D', 'W', 'L', 'D')),
      row(19, 'Club Brugge', null, 'BRU', 8, 2, 2, 4, 8, 14, 8, form('D', 'L', 'L', 'W', 'D')),
      row(20, 'Feyenoord', null, 'FEY', 8, 2, 1, 5, 10, 16, 7, form('L', 'W', 'L', 'L', 'D')),
      row(21, 'Stuttgart', null, 'VFB', 8, 1, 3, 4, 8, 14, 6, form('D', 'L', 'D', 'L', 'W')),
      row(22, 'Shakhtar', null, 'SHK', 8, 1, 2, 5, 6, 16, 5, form('L', 'D', 'L', 'L', 'W')),
      row(23, 'Red Star', null, 'CZV', 8, 1, 2, 5, 6, 18, 5, form('L', 'L', 'D', 'W', 'L')),
      row(24, 'Bologna', null, 'BOL', 8, 1, 2, 5, 6, 14, 5, form('D', 'L', 'L', 'D', 'L')),
      row(25, 'Girona', null, 'GIR', 8, 1, 1, 6, 8, 18, 4, form('L', 'L', 'W', 'L', 'L')),
      row(26, 'Sturm Graz', null, 'STU', 8, 1, 1, 6, 4, 18, 4, form('L', 'D', 'L', 'L', 'L')),
      row(27, 'Brest', null, 'SB29', 8, 1, 0, 7, 6, 20, 3, form('L', 'L', 'L', 'W', 'L')),
      row(28, 'Sparta Praha', null, 'SPP', 8, 0, 2, 6, 4, 18, 2, form('L', 'D', 'L', 'L', 'D')),
      row(29, 'RB Salzburg', null, 'RBS', 8, 0, 2, 6, 4, 20, 2, form('D', 'L', 'L', 'L', 'D')),
      row(30, 'Young Boys', null, 'YB', 8, 0, 1, 7, 4, 22, 1, form('L', 'L', 'D', 'L', 'L')),
      row(31, 'Slovan Bratislava', null, 'SLB2', 8, 0, 1, 7, 2, 24, 1, form('L', 'L', 'L', 'D', 'L')),
      row(32, 'Dinamo Zagreb', null, 'DZG', 8, 0, 1, 7, 4, 22, 1, form('L', 'D', 'L', 'L', 'L')),
      row(33, 'Leipzig', null, 'RBL', 8, 0, 0, 8, 6, 22, 0, form('L', 'L', 'L', 'L', 'L')),
      row(34, 'Stade Brestois', null, 'BRE2', 8, 0, 0, 8, 4, 24, 0, form('L', 'L', 'L', 'L', 'L')),
      row(35, 'Red Bull Salzburg', null, 'RBS2', 8, 0, 0, 8, 2, 26, 0, form('L', 'L', 'L', 'L', 'L')),
      row(36, 'Young Boys II', null, 'YB2', 8, 0, 0, 8, 2, 28, 0, form('L', 'L', 'L', 'L', 'L')),
    ].slice(0, 24), // keep table manageable - show top 24 of league phase
    allTime: [
      allTime('Real Madrid', 'real-madrid', 'RMA', 55, 620, 15),
      allTime('Milan', null, 'MIL', 48, 480, 7),
      allTime('Bayern', 'bayern-munich', 'FCB', 50, 510, 6),
      allTime('Liverpool', null, 'LIV', 42, 420, 6),
      allTime('Barcelona', 'fc-barcelona', 'BAR', 48, 490, 5),
      allTime('Ajax', null, 'AJA', 40, 280, 4),
      allTime('Inter', null, 'INT', 38, 320, 3),
      allTime('Man United', null, 'MUN', 35, 340, 3),
    ],
    leaders: {
      scorers: [
        leader(1, 'Harry Kane', 'Bayern', 'FCB', 8, null, 'bayern-munich'),
        leader(2, 'Vinícius Júnior', 'Real Madrid', 'RMA', 7, 'vinicius-junior', 'real-madrid'),
        leader(3, 'Raphinha', 'Barcelona', 'BAR', 6, null, 'fc-barcelona'),
        leader(4, 'Lautaro Martínez', 'Inter', 'INT', 6),
        leader(5, 'Erling Haaland', 'Man City', 'MCI', 5),
      ],
      assists: [
        leader(1, 'Lamine Yamal', 'Barcelona', 'BAR', 6, 'lamine-yamal', 'fc-barcelona'),
        leader(2, 'Jamal Musiala', 'Bayern', 'FCB', 5, 'jamal-musiala', 'bayern-munich'),
        leader(3, 'Florian Wirtz', 'Leverkusen', 'B04', 5),
        leader(4, 'Désiré Doué', 'PSG', 'PSG', 4, 'desire-doue', 'psg'),
        leader(5, 'Mohamed Salah', 'Liverpool', 'LIV', 4),
      ],
      cleanSheets: [
        leader(1, 'Alisson', 'Liverpool', 'LIV', 5),
        leader(2, 'Yann Sommer', 'Inter', 'INT', 4),
        leader(3, 'ter Stegen', 'Barcelona', 'BAR', 4, null, 'fc-barcelona'),
        leader(4, 'Manuel Neuer', 'Bayern', 'FCB', 3, null, 'bayern-munich'),
        leader(5, 'Thibaut Courtois', 'Real Madrid', 'RMA', 3, null, 'real-madrid'),
      ],
      cards: [
        leader(1, 'Casemiro', 'Man United', 'MUN', 4),
        leader(2, 'Araújo', 'Barcelona', 'BAR', 3, null, 'fc-barcelona'),
        leader(3, 'Upamecano', 'Bayern', 'FCB', 3, null, 'bayern-munich'),
        leader(4, 'Tchouaméni', 'Real Madrid', 'RMA', 3, null, 'real-madrid'),
        leader(5, 'Locatelli', 'Juventus', 'JUV', 3, null, 'juventus'),
      ],
    },
    bestXI: [
      xi('GK', 'Alisson', 'Liverpool', 'LIV', 45, 50, 122),
      xi('LB', 'Davies', 'Bayern', 'FCB', 50, 18, 98, null, 'bayern-munich', 19),
      xi('CB', 'Saliba', 'Arsenal', 'ARS', 80, 38, 102),
      xi('CB', 'Bastoni', 'Inter', 'INT', 70, 62, 102),
      xi('RB', 'Hakimi', 'PSG', 'PSG', 55, 82, 98, null, 'psg', 2),
      xi('CM', 'Bellingham', 'Real Madrid', 'RMA', 180, 32, 70, null, 'real-madrid', 5),
      xi('CM', 'Rodri', 'Man City', 'MCI', 100, 50, 72),
      xi('CM', 'Musiala', 'Bayern', 'FCB', 125, 68, 70, 'jamal-musiala', 'bayern-munich', 42),
      xi('LW', 'Vinícius', 'Real Madrid', 'RMA', 140, 22, 40, 'vinicius-junior', 'real-madrid', 7),
      xi('ST', 'Haaland', 'Man City', 'MCI', 180, 50, 28),
      xi('RW', 'Yamal', 'Barcelona', 'BAR', 180, 78, 40, 'lamine-yamal', 'fc-barcelona', 10),
    ],
  },
}

/* ------------------------------------------------------------------ */
/*  Lightweight catalog stubs (navigable from CompetitionsHub)         */
/* ------------------------------------------------------------------ */

function liteXI(champ, code, clubId) {
  const slots = [
    ['GK', 50, 122, 20],
    ['LB', 18, 98, 18],
    ['CB', 38, 102, 25],
    ['CB', 62, 102, 22],
    ['RB', 82, 98, 16],
    ['CM', 32, 70, 30],
    ['CM', 50, 72, 35],
    ['CM', 68, 70, 28],
    ['LW', 22, 40, 40],
    ['ST', 50, 28, 45],
    ['RW', 78, 40, 38],
  ]
  return slots.map(([pos, x, y, value], i) =>
    xi(pos, `${champ.split(' ')[0]} ${i + 1}`, champ, code, value, x, y, null, clubId, i + 1),
  )
}

/** Compact but LeagueProfile-valid competition dossier */
function makeLite(opts) {
  const {
    id,
    name,
    fullName,
    code,
    country,
    nationId = null,
    nationCode,
    continent,
    confederation,
    founded = 1990,
    type = 'domestic',
    totalValue,
    teams = 18,
    players,
    foreignersPct = 42,
    avgAge = 26.4,
    champion,
    championCode,
    championClubId = null,
    runnerUp = 'Runner-up FC',
    runnerCode = 'RU',
  } = opts

  const pld = type === 'international' ? 8 : 22
  const pl = players ?? teams * 28
  const champ = champion
  const ccode = championCode

  return {
    id,
    name,
    fullName: fullName || name,
    code,
    country,
    nationId,
    nationCode,
    continent,
    confederation: confederation || null,
    founded,
    type,
    totalValue,
    teams,
    players: pl,
    foreignersPct,
    avgAge,
    catalogStub: true,
    zones:
      type === 'international'
        ? {
            ucl: { max: 8, label: 'Knockout phase' },
            relegation: { min: Math.max(9, Math.floor(teams * 0.65)), max: teams, label: 'Eliminated' },
          }
        : {
            ucl: { max: 1, label: 'Champions' },
            relegation: { min: teams - 2, max: teams, label: 'Relegation' },
          },
    standings: [
      row(1, champ, championClubId, ccode, pld, 14, 4, 2, 42, 16, 46, form('W', 'W', 'D', 'W', 'W')),
      row(2, runnerUp, null, runnerCode, pld, 13, 5, 2, 38, 18, 44, form('W', 'D', 'W', 'W', 'L')),
      row(3, 'Third United', null, '3RD', pld, 12, 5, 3, 35, 20, 41, form('D', 'W', 'W', 'L', 'W')),
      row(4, 'Fourth City', null, '4TH', pld, 11, 6, 3, 32, 22, 39, form('W', 'L', 'D', 'W', 'D')),
      row(5, 'Fifth Athletic', null, '5TH', pld, 10, 6, 4, 30, 24, 36, form('L', 'W', 'D', 'W', 'L')),
      row(6, 'Sixth Rovers', null, '6TH', pld, 9, 7, 4, 28, 26, 34, form('D', 'D', 'W', 'L', 'W')),
    ],
    allTime: [
      allTime(champ, championClubId, ccode, 24, 920, 9),
      allTime(runnerUp, null, runnerCode, 22, 780, 6),
      allTime('Historic Rival', null, 'HRV', 20, 640, 4),
    ],
    leaders: {
      scorers: [
        leader(1, 'Lead Striker', champ, ccode, 16, null, championClubId),
        leader(2, 'Second Forward', runnerUp, runnerCode, 13),
        leader(3, 'Third Finisher', 'Third United', '3RD', 11),
      ],
      assists: [
        leader(1, 'Playmaker One', champ, ccode, 12, null, championClubId),
        leader(2, 'Creator Two', runnerUp, runnerCode, 10),
        leader(3, 'Wide Threat', 'Third United', '3RD', 8),
      ],
      cleanSheets: [
        leader(1, 'First Keeper', champ, ccode, 11, null, championClubId),
        leader(2, 'Second Keeper', runnerUp, runnerCode, 9),
        leader(3, 'Third Keeper', 'Fourth City', '4TH', 8),
      ],
      cards: [
        leader(1, 'Hard Tackler', runnerUp, runnerCode, 10),
        leader(2, 'Midfield Enforcer', champ, ccode, 9, null, championClubId),
        leader(3, 'Fullback Battler', 'Third United', '3RD', 8),
      ],
    },
    bestXI: liteXI(champ, ccode, championClubId),
  }
}

const LEAGUE_CATALOG_STUBS = {
  uel: makeLite({
    id: 'uel',
    name: 'UEFA Europa League',
    fullName: 'UEFA Europa League',
    code: 'UEL',
    country: 'Europe',
    nationId: 'uefa',
    nationCode: 'EUR',
    continent: 'Europe',
    confederation: 'UEFA',
    founded: 1971,
    type: 'international',
    totalValue: 9.6,
    teams: 36,
    players: 880,
    foreignersPct: 68,
    champion: 'Tottenham',
    championCode: 'TOT',
    runnerUp: 'Manchester United',
    runnerCode: 'MUN',
  }),
  uecl: makeLite({
    id: 'uecl',
    name: 'UEFA Conference League',
    fullName: 'UEFA Europa Conference League',
    code: 'UECL',
    country: 'Europe',
    nationId: 'uefa',
    nationCode: 'EUR',
    continent: 'Europe',
    confederation: 'UEFA',
    founded: 2021,
    type: 'international',
    totalValue: 4.2,
    teams: 36,
    players: 860,
    foreignersPct: 62,
    champion: 'Olympiacos',
    championCode: 'OLY',
    runnerUp: 'Fiorentina',
    runnerCode: 'FIO',
  }),
  'afc-cl': makeLite({
    id: 'afc-cl',
    name: 'AFC Champions League Elite',
    fullName: 'AFC Champions League Elite',
    code: 'ACL',
    country: 'Asia',
    nationCode: 'AFC',
    continent: 'Asia',
    confederation: 'AFC',
    founded: 2002,
    type: 'international',
    totalValue: 3.8,
    teams: 24,
    players: 620,
    foreignersPct: 35,
    champion: 'Al-Hilal',
    championCode: 'HIL',
    runnerUp: 'Ulsan HD',
    runnerCode: 'ULS',
  }),
  libertadores: makeLite({
    id: 'libertadores',
    name: 'Copa Libertadores',
    fullName: 'CONMEBOL Libertadores',
    code: 'LIB',
    country: 'South America',
    nationCode: 'SAM',
    continent: 'South America',
    confederation: 'CONMEBOL',
    founded: 1960,
    type: 'international',
    totalValue: 2.9,
    teams: 32,
    players: 800,
    foreignersPct: 28,
    champion: 'Botafogo',
    championCode: 'BOT',
    runnerUp: 'Atlético Mineiro',
    runnerCode: 'CAM',
  }),
  'caf-cl': makeLite({
    id: 'caf-cl',
    name: 'CAF Champions League',
    fullName: 'TotalEnergies CAF Champions League',
    code: 'CCL',
    country: 'Africa',
    nationCode: 'CAF',
    continent: 'Africa',
    confederation: 'CAF',
    founded: 1964,
    type: 'international',
    totalValue: 1.1,
    teams: 16,
    players: 420,
    foreignersPct: 22,
    champion: 'Al Ahly',
    championCode: 'AHL',
    runnerUp: 'Espérance',
    runnerCode: 'EST',
  }),
  'concacaf-cc': makeLite({
    id: 'concacaf-cc',
    name: 'Concacaf Champions Cup',
    fullName: 'Concacaf Champions Cup',
    code: 'CCC',
    country: 'North America',
    nationCode: 'NCA',
    continent: 'North America',
    confederation: 'CONCACAF',
    founded: 1962,
    type: 'international',
    totalValue: 2.4,
    teams: 27,
    players: 680,
    foreignersPct: 40,
    champion: 'Pachuca',
    championCode: 'PAC',
    runnerUp: 'Columbus Crew',
    runnerCode: 'CLB',
  }),
  'club-world-cup': makeLite({
    id: 'club-world-cup',
    name: 'FIFA Club World Cup',
    fullName: 'FIFA Club World Cup',
    code: 'CWC',
    country: 'World',
    nationCode: 'FIFA',
    continent: 'World',
    confederation: 'FIFA',
    founded: 2000,
    type: 'international',
    totalValue: 14.2,
    teams: 32,
    players: 900,
    foreignersPct: 55,
    champion: 'Real Madrid',
    championCode: 'RMA',
    championClubId: 'real-madrid',
    runnerUp: 'Pachuca',
    runnerCode: 'PAC',
  }),
  eredivisie: makeLite({
    id: 'eredivisie',
    name: 'Eredivisie',
    fullName: 'Eredivisie',
    code: 'ERE',
    country: 'Netherlands',
    nationCode: 'NED',
    continent: 'Europe',
    confederation: 'UEFA',
    founded: 1956,
    totalValue: 1.85,
    teams: 18,
    champion: 'PSV Eindhoven',
    championCode: 'PSV',
    runnerUp: 'Feyenoord',
    runnerCode: 'FEY',
  }),
  'primeira-liga': makeLite({
    id: 'primeira-liga',
    name: 'Primeira Liga',
    fullName: 'Liga Portugal Betclic',
    code: 'LIG',
    country: 'Portugal',
    nationCode: 'POR',
    continent: 'Europe',
    confederation: 'UEFA',
    founded: 1934,
    totalValue: 1.72,
    teams: 18,
    champion: 'Sporting CP',
    championCode: 'SCP',
    runnerUp: 'Benfica',
    runnerCode: 'SLB',
  }),
  'belgian-pro': makeLite({
    id: 'belgian-pro',
    name: 'Belgian Pro League',
    fullName: 'Jupiler Pro League',
    code: 'BPL',
    country: 'Belgium',
    nationCode: 'BEL',
    continent: 'Europe',
    confederation: 'UEFA',
    founded: 1895,
    totalValue: 1.28,
    teams: 16,
    champion: 'Club Brugge',
    championCode: 'CLU',
    runnerUp: 'Union SG',
    runnerCode: 'USG',
  }),
  championship: makeLite({
    id: 'championship',
    name: 'Championship',
    fullName: 'Sky Bet Championship',
    code: 'CHP',
    country: 'England',
    nationId: 'england',
    nationCode: 'ENG',
    continent: 'Europe',
    confederation: 'UEFA',
    founded: 2004,
    totalValue: 1.95,
    teams: 24,
    champion: 'Leeds United',
    championCode: 'LEE',
    runnerUp: 'Burnley',
    runnerCode: 'BUR',
  }),
  'brasileirao': makeLite({
    id: 'brasileirao',
    name: 'Brasileirão Série A',
    fullName: 'Campeonato Brasileiro Série A',
    code: 'BRA',
    country: 'Brazil',
    nationCode: 'BRA',
    continent: 'South America',
    confederation: 'CONMEBOL',
    founded: 1959,
    totalValue: 2.15,
    teams: 20,
    champion: 'Botafogo',
    championCode: 'BOT',
    runnerUp: 'Palmeiras',
    runnerCode: 'PAL',
  }),
  'liga-profesional': makeLite({
    id: 'liga-profesional',
    name: 'Liga Profesional',
    fullName: 'Liga Profesional de Fútbol',
    code: 'LPF',
    country: 'Argentina',
    nationCode: 'ARG',
    continent: 'South America',
    confederation: 'CONMEBOL',
    founded: 1891,
    totalValue: 1.05,
    teams: 28,
    champion: 'Vélez Sarsfield',
    championCode: 'VEL',
    runnerUp: 'Talleres',
    runnerCode: 'TAL',
  }),
  mls: makeLite({
    id: 'mls',
    name: 'Major League Soccer',
    fullName: 'Major League Soccer',
    code: 'MLS',
    country: 'USA / Canada',
    nationCode: 'USA',
    continent: 'North America',
    confederation: 'CONCACAF',
    founded: 1996,
    totalValue: 1.65,
    teams: 30,
    champion: 'LA Galaxy',
    championCode: 'LAG',
    runnerUp: 'New York Red Bulls',
    runnerCode: 'RBNY',
  }),
  'liga-mx': makeLite({
    id: 'liga-mx',
    name: 'Liga MX',
    fullName: 'Liga BBVA MX',
    code: 'LMX',
    country: 'Mexico',
    nationCode: 'MEX',
    continent: 'North America',
    confederation: 'CONCACAF',
    founded: 1943,
    totalValue: 1.42,
    teams: 18,
    champion: 'América',
    championCode: 'AME',
    runnerUp: 'Cruz Azul',
    runnerCode: 'CAZ',
  }),
  'saudi-pro': makeLite({
    id: 'saudi-pro',
    name: 'Saudi Pro League',
    fullName: 'Roshn Saudi League',
    code: 'SPL',
    country: 'Saudi Arabia',
    nationCode: 'KSA',
    continent: 'Asia',
    confederation: 'AFC',
    founded: 1976,
    totalValue: 2.85,
    teams: 18,
    champion: 'Al-Hilal',
    championCode: 'HIL',
    runnerUp: 'Al-Nassr',
    runnerCode: 'NSR',
  }),
  'j1-league': makeLite({
    id: 'j1-league',
    name: 'J1 League',
    fullName: 'Meiji Yasuda J1 League',
    code: 'J1',
    country: 'Japan',
    nationCode: 'JPN',
    continent: 'Asia',
    confederation: 'AFC',
    founded: 1993,
    totalValue: 0.92,
    teams: 20,
    champion: 'Vissel Kobe',
    championCode: 'VK',
    runnerUp: 'Yokohama F. Marinos',
    runnerCode: 'YFM',
  }),
  'egyptian-premier': makeLite({
    id: 'egyptian-premier',
    name: 'Egyptian Premier League',
    fullName: 'Nile League',
    code: 'EPL',
    country: 'Egypt',
    nationCode: 'EGY',
    continent: 'Africa',
    confederation: 'CAF',
    founded: 1948,
    totalValue: 0.48,
    teams: 18,
    champion: 'Al Ahly',
    championCode: 'AHL',
    runnerUp: 'Zamalek',
    runnerCode: 'ZAM',
  }),
  'a-league': makeLite({
    id: 'a-league',
    name: 'A-League Men',
    fullName: 'Isuzu UTE A-League',
    code: 'AUS',
    country: 'Australia',
    nationCode: 'AUS',
    continent: 'Oceania',
    confederation: 'AFC',
    founded: 2004,
    totalValue: 0.28,
    teams: 13,
    champion: 'Central Coast Mariners',
    championCode: 'CCM',
    runnerUp: 'Melbourne Victory',
    runnerCode: 'MVC',
  }),
}

Object.assign(LEAGUES_DETAIL, LEAGUE_CATALOG_STUBS)

/** League / competition codes → league profile ids (global linking) */
export const LEAGUE_CODE_TO_ID = {
  // nation / home cards
  ENG: 'premier-league',
  ESP: 'la-liga',
  GER: 'bundesliga',
  ITA: 'serie-a',
  FRA: 'ligue-1',
  TUR: 'super-lig',
  // competition codes used on clubs / matches
  PRL: 'premier-league',
  LAL: 'la-liga',
  BUN: 'bundesliga',
  SEA: 'serie-a',
  LI1: 'ligue-1',
  SÜP: 'super-lig',
  UCL: 'ucl',
  UEL: 'uel',
  UECL: 'uecl',
  ACL: 'afc-cl',
  LIB: 'libertadores',
  CCL: 'caf-cl',
  CCC: 'concacaf-cc',
  CWC: 'club-world-cup',
  ERE: 'eredivisie',
  LIG: 'primeira-liga',
  BPL: 'belgian-pro',
  CHP: 'championship',
  BRA: 'brasileirao',
  LPF: 'liga-profesional',
  MLS: 'mls',
  LMX: 'liga-mx',
  SPL: 'saudi-pro',
  J1: 'j1-league',
  EPL: 'egyptian-premier',
  AUS: 'a-league',
}

/** Display names → league profile ids */
export const LEAGUE_NAME_TO_ID = {
  'La Liga': 'la-liga',
  'Premier League': 'premier-league',
  Bundesliga: 'bundesliga',
  'Serie A': 'serie-a',
  'Ligue 1': 'ligue-1',
  'Trendyol Süper Lig': 'super-lig',
  'Süper Lig': 'super-lig',
  'UEFA Champions League': 'ucl',
  'Champions League': 'ucl',
  'UEFA Europa League': 'uel',
  'Europa League': 'uel',
  'UEFA Conference League': 'uecl',
  'AFC Champions League Elite': 'afc-cl',
  'AFC Champions League': 'afc-cl',
  'Copa Libertadores': 'libertadores',
  'CAF Champions League': 'caf-cl',
  'Concacaf Champions Cup': 'concacaf-cc',
  'FIFA Club World Cup': 'club-world-cup',
  Eredivisie: 'eredivisie',
  'Primeira Liga': 'primeira-liga',
  'Belgian Pro League': 'belgian-pro',
  Championship: 'championship',
  'Brasileirão Série A': 'brasileirao',
  'Liga Profesional': 'liga-profesional',
  'Major League Soccer': 'mls',
  'Liga MX': 'liga-mx',
  'Saudi Pro League': 'saudi-pro',
  'J1 League': 'j1-league',
  'Egyptian Premier League': 'egyptian-premier',
  'A-League Men': 'a-league',
}

/* Nations live in nationData.js (full ecosystem archives) */
export { NATIONS } from './nationData.js'
